generator:
  class: sfDoctrineGenerator
  param:
    model_class:           modescourrier
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          modescourrier
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          mode: { label: "Type courrier"}
      list:    
          title: Liste des types courriers
          display: [mode]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche type courrier %%mode%%
      new:     
          title: Nouvelle fiche type courrier
