generator:
  class: sfDoctrineGenerator
  param:
    model_class:           piecejoint
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          piecejoint
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_typepiece: { label: "Type Pièce"}
          objet: { label: "Object"}
          typepiece: { label: "Type Pièce"}
          id_courrier: { label: "Courrier"}
          id_parcour: { label: "Courrier Transféré"}
          sujet: { label: "Observation"}
      list:    
          title: Liste des Pièces-Jointes
          display: [objet,courrier]
      filter:  
          display: [id_courrier]
      form:    ~
      edit:    
          title: Mise à jour courrier - %%courrier%% -
      new:     ~
