generator:
  class: sfDoctrineGenerator
  param:
    model_class:           unitemarche
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          unitemarche
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Libellé"}
      list:    
          title: Liste des Unités
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: mise à jour Unité
      new:     
          title: nouvelle fiche Unité
