generator:
  class: sfDoctrineGenerator
  param:
    model_class:           destinatonvisitemedicale
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          destinatonvisitemedicale
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Libellé"}
          nbrjour: { label: "Nombre Jour "}
          
      list:    
          title: Liste des Destinations du Visite Médicale
          display: [libelle,nbrjour]
      filter:  
          display: [libelle,nbrjour]
      form:    ~
      edit:    
          title: Mise à jour fiche Destination du Visite Médicale
      new:     
          title: Nouvelle fiche Destination du Visite Médicale
