generator:
  class: sfDoctrineGenerator
  param:
    model_class:           visaachat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          visaachat
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_agent: { label: "Personnel"}
          libelle: { label : "Nom du visa"}
          chemin: { label: "Image"}
          imagevisa: { label: "Image visa"}
      list:    
          title: Liste des visas
          display: [libelle,agents,imagevisa]
      filter:  
          display: [libelle,id_agent]
      form:    ~
      edit:    
          title: Mise à jour %%libelle%%
      new:     
          title: Nouvelle fiche visa
