evaluation:
  class: sfDoctrineRouteCollection
  options:
    model:                evaluation
    module:               evaluation
    prefix_path:          /evaluation
    column:               id
    with_wildcard_routes: true

sousrubrique:
  class: sfDoctrineRouteCollection
  options:
    model:                sousrubrique
    module:               sousrubrique
    prefix_path:          /sousrubrique
    column:               id
    with_wildcard_routes: true

rubriqueformation:
  class: sfDoctrineRouteCollection
  options:
    model:                rubriqueformation
    module:               rubriqueformation
    prefix_path:          /rubriqueformation
    column:               id
    with_wildcard_routes: true

ristourne:
  class: sfDoctrineRouteCollection
  options:
    model:                ristourne
    module:               ristourne
    prefix_path:          /ristourne
    column:               id
    with_wildcard_routes: true

regroupementtheme:
  class: sfDoctrineRouteCollection
  options:
    model:                regroupementtheme
    module:               regroupementtheme
    prefix_path:          /regroupementtheme
    column:               id
    with_wildcard_routes: true

planing:
  class: sfDoctrineRouteCollection
  options:
    model:                planing
    module:               planing
    prefix_path:          /planing
    column:               id
    with_wildcard_routes: true

organisme:
  class: sfDoctrineRouteCollection
  options:
    model:                organisme
    module:               organisme
    prefix_path:          /organisme
    column:               id
    with_wildcard_routes: true

modalitedecalcul:
  class: sfDoctrineRouteCollection
  options:
    model:                modalitedecalcul
    module:               modalitedecalcul
    prefix_path:          /modalitedecalcul
    column:               id
    with_wildcard_routes: true

formateur:
  class: sfDoctrineRouteCollection
  options:
    model:                formateur
    module:               formateur
    prefix_path:          /formateur
    column:               id
    with_wildcard_routes: true

domaineuntilisation:
  class: sfDoctrineRouteCollection
  options:
    model:                domaineuntilisation
    module:               domaineuntilisation
    prefix_path:          /domaineuntilisation
    column:               id
    with_wildcard_routes: true

besoinsdeformation:
  class: sfDoctrineRouteCollection
  options:
    model:                besoinsdeformation
    module:               besoinsdeformation
    prefix_path:          /besoinsdeformation
    column:               id
    with_wildcard_routes: true

baserustourne:
  class: sfDoctrineRouteCollection
  options:
    model:                baserustourne
    module:               baserustourne
    prefix_path:          /baserustourne
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: besoinsdeformation, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
