generator:
  class: sfDoctrineGenerator
  param:
    model_class:           direction
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          direction
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
          id_site : { label: "Site"}
          id_projet : { label: "Projet"}
      list:    
          title: Liste des Directions
          display: [libelle]
      filter: 
          display: [libelle]
          
      form:    ~
      edit:    
          title: Mise à jour fiche Direction
      new:     
          title: Nouvelle fiche Direction
