generator:
  class: sfDoctrineGenerator
  param:
    model_class:           prevelege
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          prevelege
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          nomprevelege: { label: "Privilège"}
      list:    
          title: Liste des Privilèges
          display: [nomprevelege]
          max_per_page: 10
      filter:  ~
      form:    ~
      edit:    
          title: Modifier %%nomprevelege%%
      new:     
          title: Nouveau privilège
