generator:
  class: sfDoctrineGenerator
  param:
    model_class:           typetransfert
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          typetransfert
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Type de Transfert"}
      list:    
        title: Liste des Types de Transferts
        display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour type de transfert %%libelle%%
      new:     
          title: Nouvelle fiche de type de transfert
