generator:
  class: sfDoctrineGenerator
  param:
    model_class:           actionparcour
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          actionparcour
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          action: {label: "Action d'envoie"}
      list:    
          title: Liste des Actions
          display: [action]
      filter:  
          display: [action]
      form:    ~
      edit:    
          title: Mise à jour action - %%action%% -
      new:     
          title: Nouvelle fiche d'action 
