generator:
  class: sfDoctrineGenerator
  param:
    model_class:           contratachat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contratachat
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          reference: {label: "Référence"}
          datecreation: { label: "Date de création"}
          observation: { label: "Observation"}
          id_demandeur: { label: "Demandeur"}
          id_typedoc: { label: "Type doc."}
          id_adresse: { label: "Adresse"}
          id_lignedirectionsite: { label: "Direction par site"}
          desiegnation: { label: "Désiegnation"}
          id_objet: { label: "Objet"}
          id_projet: { label: "Projet"}
          mht: { label: "Mnt. HT"}
          mnttva: { label: "Mnt. TVA"}
          mntttc: { label: "Mnt. TTC"}
          numerodocachat: { label: "Numéro" }
          typeparnumero: { label: "Type"}
          datecreationachat: { label: "Date création"}
          etatdocument: {label: "Etat"}
          id_etatdoc: { label: "Etat"}
          id_frs: { label: "Fournisseur"}
          id_typedoc:  { label: "Type document achat"}
      list:    
          title: Liste des Fiches Contrats
          display: [datecreation,numero,reference,fournisseur,etatdocument]
          object_actions:
            _edit:      ~
#          batch_actions: {}
          max_per_page: 5
      filter:  
           display: [numero,datecreation,reference,id_frs]
      form:    
          actions:
             _list:   ~
             _save:   ~
      edit:   
          title: MODIFIER FICHE CONTRAT %%numero%%
      new:     
          title: NOUVELLE FICHE CONTRAT
