generator:
  class: sfDoctrineGenerator
  param:
    model_class:           formulaire
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          formulaire
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
           id_agents : { label: "Agents"}
           
      list:    
          title: Liste des Formulaires  
          display: [agents]
      filter:  
          display: [id_agents]
      form:    ~
      edit:    
          title: Mise a jour  Formulaire 
      new:     
          title: Nouvelle  Formulaire

