generator:
  class: sfDoctrineGenerator
  param:
    model_class:           baserustourne
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          baserustourne
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          
           
           libelle : { label: "Base Ristourne"}
           id_sousrubrique : {label: " Sous Rubrique "}
       
      list:    
          title: Liste des Bases Ristourne
          display: [sousrubrique,libelle]
      filter:  
          display: [id_sousrubrique,libelle]
      form:    ~
      edit:   
          title: Mise à jour fiche
      new: 
          title: Nouvelle fiche 