generator:
  class: sfDoctrineGenerator
  param:
    model_class:           categorierh
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          categorierh
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
          id_ccorps : { label: "Corps"}
          souscorps : { label: "Sous Corps"}
          
      list:   
          title: Liste des Catégories 
          display: [corps,souscorps,libelle]
      filter:  ~
      form:    ~
      edit:   
          title: Mise a jour Fiche Catégorie
      new:     
          title: Nouvelle Fiche Catégorie