generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sourcepret
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sourcepret
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
          sourcepret : { label: "Source Prêt "}
          id_source : { label: "Source Prêt "}
          
      list:   
          title: Liste des Source des Prêts 
          display: [libelle]
      filter:  
           display: [libelle]
      form:    ~
      edit:   
          title: Mise a jour Fiche Source de Prêt
      new:     
          title: Nouvelle Fiche Source de Prêt

