generator:
  class: sfDoctrineGenerator
  param:
    model_class:           naturediscipline
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          naturediscipline
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
          id_agents : { label: "Agents"}
          id_typediscipline : {label: "Type Discipline"}
      list:    
          title: Liste des  Natures Disciplines 
          display: [libelle]
      filter: 
          display: [libelle]
          
      form:    ~
      edit:    
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche 
