generator:
  class: sfDoctrineGenerator
  param:
    model_class:           fabricant
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fabricant
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Listes des Fabricant
      filter:  ~
      form:    ~
      edit:
        title: Modifier %%fabricant%%
      new:
        title: Noveau Fabricant
