generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sourcesfinancemment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sourcesfinancemment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sourcefinancement: { label: "Source de financement"}
      list:
        title: Liste des Sources de Financement
        display: [sourcefinancement]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
