generator:
  class: sfDoctrineGenerator
  param:
    model_class:           unite
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          unite
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
          id_service: {label: "Service"}
          servicerh: {label: "Service"}
      list:    
          title: Liste des Unités
          display: [servicerh,libelle]
      filter: 
          display: [id_service,libelle]
          
      form:    ~
      edit:    
          title: Mise à jour fiche Unité
      new:     
          title: Nouvelle fiche Unité
