generator:
  class: sfDoctrineGenerator
  param:
    model_class:           fonction
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fonction
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      
      list:    
          title: Liste des fonctions
          display: [description]
      filter:  ~
      form:    ~
      edit:   
          title: Mise à jour fiche
      new: 
          title: Nouvelle fiche 
