generator:
  class: sfDoctrineGenerator
  param:
    model_class:           codesociale
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          codesociale
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          code : { label: "Code"}
          libelle : { label: "Libellé"}
          taux : { label: "Taux de contribution Salariale"}
          
      list:    
          title: Liste des Caisses de Sécurité Sociales
          display: [code,libelle]
      filter: 
          display: [code,libelle]
          
      form:    ~
      edit:    
          title: Mise à jour fiche Caisses de Sécurité Sociales
      new:     
          title: Nouvelle fiche Caisses de Sécurité Sociales
