generator:
  class: sfDoctrineGenerator
  param:
    model_class:           parametreexpedition
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          parametreexpedition
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_exp: { label : "Expéditeurs"}
          id_dest: { label: "Récepteurs"}
          destinationexpdest: { label: "Destination"}
          id_typecourrier: { label: "Type de courrier"}
          typecourrier: { label: "Type de courrier"}
          expdest: { label: "Expéditeur"}
      list:    
          title: Paramètres d'éxpeditions
          display: [typecourrier,expdest,destinationexpdest]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche - %%typecourrier%% %%expdest%% -
      new:     
          title: Nouvelle fiche 
