generator:
  class: sfDoctrineGenerator
  param:
    model_class:           demandeavancepret
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          demandeavancepret
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_agents : { label: "Agents"}
          id_type : { label: "Type"}
          datedemande: {label: "Date de Demande"}
        
      list:    
          title: Liste des Deamndes
          display: [agents]
      filter:  
          
          display: [id_agents]
      form:    ~
      edit:   
          title: Mise à jour Demande 
      new:     
          title: Nouvelle fiche Demande

