generator:
  class: sfDoctrineGenerator
  param:
    model_class:           parametragesociete
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          parametragesociete
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_societe: { label: "Société"}
          valeurfodec: { label: "Valeur Fodec"}
          is_engnegative: {label: "Accepter les engagements négatifs"}
      list:    
          title: Paramétrages sociétés
          display: [valeurfodec,societe]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à ajour 
      new:     
          title: Nouveaux paramétrages
