generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Motifabsenceinactive
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          motifabsenceinactive
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
           libelle: {label: "Motif Absence"}
      list:    
          title: Liste des Motifs d'Absences
          display: [libelle]
      filter:  ~
      form:    ~
      edit:   
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche 
