generator:
  class: sfDoctrineGenerator
  param:
    model_class:           categorieoperation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          categorieoperation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Catégorie d'opération"}
      list:    
          title: Liste des catégories d'opération
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche catégorie d'oprération
      new:     
          title: Nouvelle fiche catégorie d'opération