generator:
  class: sfDoctrineGenerator
  param:
    model_class:           typearticle
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          typearticle
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Type Article"}
      list:    
          title: Liste des types articles
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour type - %%libelle%%
      new:     
          title: Nouveau Type
