generator:
  class: sfDoctrineGenerator
  param:
    model_class:           modeleapro
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          modeleapro
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          libelle: {label: "Libellé"}
      list:
          title: Liste des modèles d'approvisionnement du stocks
          display: [libelle]
          max_per_page: 5
      filter:  ~
      form:    ~
      edit:
          title: Modifier %%libelle%%
      new:
          title: Nouveau modèle d'approvisionnement du stocks
