generator:
  class: sfDoctrineGenerator
  param:
    model_class:           souscorps
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          souscorps
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_corps : { label: "Corps"}
          libelle : { label: "Libellé"}
      list:    
          title: Liste des Sous Corps
          display: [corps,libelle]
      filter:  ~
      form:    ~
      edit:   
          title: Mise à jour fiche Sous Corps
      new:     
          title: Nouvelle fiche Sous Corps
