generator:
  class: sfDoctrineGenerator
  param:
    model_class:           experiences
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          experiences
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          duree : { label: "Durée"}
          organistaion : {label: "Organisation"}
          description : { label: "Description"}
          id_agents : {label: "Agents"}
          id_typeexperience : {label: "Type Experience"}

      list:    
          title: Liste des experiences
          display: [description,organistaion,duree]
      filter:  
          display: [description,organistaion,duree]
      form:    ~
      edit:    
          title: Mise a jour Fiche
      new:     
          title: Nouvelle Fiche 
