generator:
  class: sfDoctrineGenerator
  param:
    model_class:           typebureaux
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          typebureaux
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        typebureaux: { label: "Liste des locaux"}
      list:
        title: Liste des locaux
        display: [typebureaux]
      filter:  ~
      form:    ~
      edit:
        title: Modifier %%typebureaux%%
      new:
        title: Nouveau local
