generator:
  class: sfDoctrineGenerator
  param:
    model_class:           demandedevoirfichieradmin
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          demandedevoirfichieradmin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
           id_agents : { label: "Agents"}
           id_service : { label: "Service"}
      list:    
          title: Liste des demandes de voir des Fichiers Administratifs
          display: [agents]
      filter:  
          display: [id_agents]
      form:    ~
      edit:    
          title: Mise a jour Fiche 
      new:     
          title: Nouvelle Fiche  
