generator:
  class: sfDoctrineGenerator
  param:
    model_class:           regroupementagents
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          regroupementagents
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
         
           libelle : { label: "Libellé"}
      list:    
          title: Liste des Regroupements Agents
          display : [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche
      new:    
          title: Nouvelle fiche