societe:
  class: sfDoctrineRouteCollection
  options:
    model:                societe
    module:               societe
    prefix_path:          /societe
    column:               id
    with_wildcard_routes: true

regimehoraire:
  class: sfDoctrineRouteCollection
  options:
    model:                regimehoraire
    module:               regimehoraire
    prefix_path:          /regimehoraire
    column:               id
    with_wildcard_routes: true

entetepaie:
  class: sfDoctrineRouteCollection
  options:
    model:                entetepaie
    module:               entetepaie
    prefix_path:          /entetepaie
    column:               id
    with_wildcard_routes: true

paiement:
  class: sfDoctrineRouteCollection
  options:
    model:                paiement
    module:               paiement
    prefix_path:          /paiement
    column:               id
    with_wildcard_routes: true

paie:
  class: sfDoctrineRouteCollection
  options:
    model:                paie
    module:               paie
    prefix_path:          /paie
    column:               id
    with_wildcard_routes: true

baremeimpot:
  class: sfDoctrineRouteCollection
  options:
    model:                baremeimpot
    module:               baremeimpot
    prefix_path:          /baremeimpot
    column:               id
    with_wildcard_routes: true

agents:
  class: sfDoctrineRouteCollection
  options:
    model:                agents
    module:               agents
    prefix_path:          /agents
    column:               id
    with_wildcard_routes: true

dossiercomptable:
  class: sfDoctrineRouteCollection
  options:
    model:                dossiercomptable
    module:               dossiercomptable
    prefix_path:          /dossiercomptable
    column:               id
    with_wildcard_routes: true

deductioncommune:
  class: sfDoctrineRouteCollection
  options:
    model:                deductioncommune
    module:               deductioncommune
    prefix_path:          /deductioncommune
    column:               id
    with_wildcard_routes: true

formuleprimes:
  class: sfDoctrineRouteCollection
  options:
    model:                formuleprimes
    module:               formuleprimes
    prefix_path:          /formuleprimes
    column:               id
    with_wildcard_routes: true

contribitionpatronale:
  class: sfDoctrineRouteCollection
  options:
    model:                contribitionpatronale
    module:               contribitionpatronale
    prefix_path:          /contribitionpatronale
    column:               id
    with_wildcard_routes: true

codesociale:
  class: sfDoctrineRouteCollection
  options:
    model:                codesociale
    module:               codesociale
    prefix_path:          /codesociale
    column:               id
    with_wildcard_routes: true

primes:
  class: sfDoctrineRouteCollection
  options:
    model:                primes
    module:               primes
    prefix_path:          /primes
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: accueil, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
