generator:
  class: sfDoctrineGenerator
  param:
    model_class:           application
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          application
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          libelle: {label: "Libellé"}
      list:
          title: Liste des Modules E.R.P
          display: [libelle]
          max_per_page: 10
      filter:
          display: [libelle]
      form:    ~
      edit:
          title: Modifier %%libelle%%
      new:
          title: Nouveau Module E.R.P
