motif:
  class: sfDoctrineRouteCollection
  options:
    model:                motif
    module:               motif
    prefix_path:          /motif
    column:               id
    with_wildcard_routes: true

conge:
  class: sfDoctrineRouteCollection
  options:
    model:                conge
    module:               conge
    prefix_path:          /conge
    column:               id
    with_wildcard_routes: true

jourferier:
  class: sfDoctrineRouteCollection
  options:
    model:                jourferier
    module:               jourferier
    prefix_path:          /jourferier
    column:               id
    with_wildcard_routes: true

presence:
  class: sfDoctrineRouteCollection
  options:
    model:                presence
    module:               presence
    prefix_path:          /presence
    column:               id
    with_wildcard_routes: true

naturecertif:
  class: sfDoctrineRouteCollection
  options:
    model:                naturecertif
    module:               naturecertif
    prefix_path:          /naturecertif
    column:               id
    with_wildcard_routes: true

typeconge:
  class: sfDoctrineRouteCollection
  options:
    model:                typeconge
    module:               typeconge
    prefix_path:          /typeconge
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: typeconge, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
