generator:
  class: sfDoctrineGenerator
  param:
    model_class:           souscorps
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          souscorps
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
          id_corps : { label: "Corps"}
      list:    
          title: Liste des Sous Corps
          display: [libelle,corps]
      filter:  ~
      form:    ~
      edit:   
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche
