generator:
  class: sfDoctrineGenerator
  param:
    model_class: dossierfourniseur
    theme: admin
    non_verbose_templates: true
    with_show: false
    singular: ~
    plural: ~
    route_prefix: dossierfourniseur
    with_doctrine_route: true
    actions_base_class: sfActions

    config:
      actions: ~
      fields:
        id_frs: { label: "Fournisseur" }
        name: { label: "Name Dossier" }

      list:
        title: Liste des Dossiers Fournisseur
        display: [name, datecreation, fournisseur]
        max_per_page: 10
      filter:
        display: [name, datecreation, id_frs]
      form:
        actions:
          _list: ~
          _save: ~
      edit:
        title: MODIFIER Dossier Fournisseur
      new:
        title: NOUVEAU Dossier Fournisseur
