generator:
  class: sfDoctrineGenerator
  param:
    model_class:           role
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          role
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        role: {label: "Role"}
        id_famexpdes: {label: "Famille Expéditeur / Destinataire"}
        famexpdes: {label: "Famille Expéditeur / Destinataire"}
      list:
        title: Liste des Roles
        display: [role,famexpdes]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:
        title: Modifier %%role%%
      new:
        title: Nouveau Role Utilisateur
