generator:
  class: sfDoctrineGenerator
  param:
    model_class:           motif
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          motif
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
           libelle : { label: "Libellé "}         
      list:    
          title: Liste des  Motifs d'absence
          display: [code,libelle]
      filter:  
          display: [libelle]
      form:    ~
      edit:   
          title: Mise à jour fiche
      new: 
          title: Nouvelle fiche 
