generator:
  class: sfDoctrineGenerator
  param:
    model_class:           salaireouvrier
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          salaireouvrier
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
         id_contratouvrier: {label: "Contrat ouvrier"}
      list:    
          title: Liste des Pointages
          display: [contratouvrier,salaire]
      filter: 
          display: [id_contratouvrier]
          
      form:    ~
      edit:    
          title: Mise à jour fiche Pointage
      new:     
          title: Nouvelle fiche Pointage
