generator:
  class: sfDoctrineGenerator
  param:
    model_class:           corps
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          corps
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
           libelle : { label: "Libellé"}
          
      list:    
          title: Liste des Filières
          display: [libelle]
      filter:  ~
      form:    ~
      edit:   
          title: Mise à jour fiche Filière
      new:     
          title: Nouvelle fiche Filière
