generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ligneniveuxeducatif
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ligneniveuxeducatif
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          description : { label: "Description"}
       
          id_niveaueducatif : { label: "Niveau educatif"}
          id_agents : {label: "Agents"}
      list:    
          title: Liste des Niveau educatifs
          display: [description,id_agents,id_niveaueducatif]
      filter: 
          display: [description,id_agents,id_niveaueducatif]
          
      form:    ~
      edit:    
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche 
