generator:
  class: sfDoctrineGenerator
  param:
    model_class:           gouvernerat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gouvernerat
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_pays: {label: "Pays"}
      list:    
          title: Liste des Gouvernerats
          display : [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche
