generator:
  class: sfDoctrineGenerator
  param:
    model_class:           lieulivraisson
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lieulivraisson
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Lieu de livraison"}
      list:    
          title: Liste des points de livraison
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche lieu de livraison %%libelle%%
      new:     
          title: Nouvelle fiche lieu de livraison
