generator:
  class: sfDoctrineGenerator
  param:
    model_class:           besoinsdeformation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          besoinsdeformation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          
           
           besoins : { label: "Besoin de Formation"}
           id_agents : {label: "  Agents "}
           annee : {label: "  Année "}
       
      list:    
          title: Liste des Besoins de Formation 
          display: [agents,besoins]
      filter:  
          display: [id_agents,besoins,annee]
      form:    ~
      edit:   
          title: Mise à jour fiche
      new: 
          title: Nouvelle fiche
