generator:
  class: sfDoctrineGenerator
  param:
    model_class:           paie
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          paie
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_agents : { label: "Agent"}
          agents : { label: "Agent"}
          mois : { label: "Mois"}
          annee : { label: "Année"}
          salairenet : { label: "Salaire Net"}
          salaireimposable : { label: "Salaire Imposable"}
          netapayyer : { label: "Net à Payer"}
          
      list:    
          title: Liste des Fiches de Paie
          display: [agents,mois,annee,salaireimposable,salairenet,netapayyer]
      filter: 
          display: [id_agents]
      form:    ~
      edit:    
          title: Mise à jour fiche 
      new:     
          title: Nouvelle fiche 