generator:
  class: sfDoctrineGenerator
  param:
    model_class:           unitemarche
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          unitemarche
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          libelle: { label: "Unité de mesure"}
      list:    
          title: Liste des unités de mesures
          display: [ libelle]
      filter:  ~
      form:    ~
      edit:
          title: Mise à jour unité de mesure - %%libelle%%
      new:
          title: Nouvelle unité de mesure
