generator:
  class: sfDoctrineGenerator
  param:
    model_class:           etage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          etage
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_site: { label: "Site"}
      list:
        title: Liste des Etage
        display: [ site,etage]
      filter:  ~
      form:    ~
      edit:
        title: Modifier  %%etage%%
      new:
        title: Nouveaux Etage
