generator:
  class: sfDoctrineGenerator
  param:
    model_class:           notesbce
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notesbce
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Modalité de paiement"}
      list:    
          title: Liste des Modalités de paiements
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche 
      new:     
          title: Nouvelle fiche
