generator:
  class: sfDoctrineGenerator
  param:
    model_class:           avis
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          avis
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_poste: { label: "Poste"}
          libelle: { label: "Avis"}
      list:    
          title: Liste des Avis
          display: [libelle,poste]
          max_per_page: 10
      filter:  
          display: [id_poste]
      form:    ~
      edit:    
          title: Mise à jour %%libelle%%
      new:     
          title: Nouvelle fiche
