generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sexe
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sexe
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
      list:    
          title: Liste des sexes 
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise a jour Fiche
      new:     
          title: Nouveau Fiche 
