generator:
  class: sfDoctrineGenerator
  param:
    model_class:           pays
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pays
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des Pays
        display: [pays]
      filter:  ~
      form:    
      edit:
        title: Modifier Pays
      new:
        title: Nouveau Pays
