generator:
  class: sfDoctrineGenerator
  param:
    model_class:           gouvernera
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gouvernera
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id_pays: {label: "Pays"}
        gouvernera: { label: "Gouvernorat"}
      list:
        title: Liste des Gouvernorats
        display: [pays,gouvernera]
      filter:  ~
      form:    ~
      edit:
        title: Modifier Gouvernorat
      new:
        title: Nouveau Gouvernorat
