generator:
  class: sfDoctrineGenerator
  param:
    model_class:           contratouvrier
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contratouvrier
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_ouvrier : { label: "Ouvrier (عامل الحضيرة )"}
          daterecrutement : { label: "Date de Recrutement (تاريخ الإنتداب )"}
          datedebutcontrat : { label: "Date de Debut de contrat (بداية العقد  )"}
          datefincontrat : { label: "Date de fin contrat (نهاية العقد)"}
          id_situationadmini : { label: "Situation administrative"}
#        
      list:    
          title: Liste des Contrats
          display: [ouvrier,daterecrutement,datedebutcontrat,datefincontrat]
      filter: 
          display: [id_ouvrier]
          
      form:    ~
      edit:    
          title: Mise à jour fiche Contrat
      new:     
          title: Nouvelle fiche Contrat