generator:
  class: sfDoctrineGenerator
  param:
    model_class:           typepermis
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          typepermis
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
      list:    
          title: Liste des types de permis 
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche
      new:   
          title: Nouvelle fiche
