<?php

/**
 * AvisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvisTable
     */
    public static function getInstance(){
        return Doctrine_Core::getTable('Avis');
    }
    
    public function getByPoste($poste) {
        $q = $this->createQuery('a')
                ->where('a.id_poste = ?', $poste)
                ->orderBy('a.nordre')
                ->execute();
        return $q;
    }
}