<?php

/**
 * BanqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BanqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BanqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Banque');
    }
}