<?php

/**
 * CongeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CongeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CongeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conge');
    }
}