<?php

/**
 * Contratachat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contratachat extends BaseContratachat {

    public function __toString() {
        return "Contrat N° " . $this->getNumero();
    }

    public function ActionSignatureContratProvioire($iddoc) {
        $html = "";
        $contrat = ContratachatTable::getInstance()->findOneById($iddoc);
        $doc_acha = DocumentachatTable::getInstance()->findOneByIdContrat($iddoc);
        //  die($doc_acha->getId().'fcdddddd'.$iddoc);

        $p = new Piecejointbudget();
        $piece = PiecejointbudgetTable::getInstance()->findOneByIdDocachat($doc_acha->getId());

        if ($piece) {
            $p = $piece;
            return $p->getDocumentbudget()->getLigprotitrub()->getTitreEtRubrique();
        }

//        if (sizeof($doc_acha) >= 1) {
//            if ($doc_acha->getIdDocparent() != null && $doc_acha->getIdDocparent() != '')
//                $id_docacha = $doc_acha->getIdDocparent();
//            $document_achat = DocumentachatTable::getInstance()->findOnebyId($id_docacha);
////die($doc_acha->getId().'mp');
//            $html = "";
//
//            $lg = new ligavisdoc();
//            if (count($document_achat) > 1) {
////            if($doc_acha->getId().'mp');
////                $piece_provisoire = Doctrine_Core::getTable('ligavisdoc')->findOneByIdDoc($document_achat->getId());
////
////                if ($piece_provisoire) {
////                    $pie = $piece_provisoire;
////                    return $pie->getLigprotitrub()->getTitreEtRubrique();
////                }
//                $p = new Piecejointbudget();
//                $piece = Doctrine_Core::getTable('piecejointbudget')->findOneByIdDocachat($doc_acha->getId());
//
//                if ($piece) {
//                    $p = $piece;
//                    return $p->getDocumentbudget()->getLigprotitrub()->getTitreEtRubrique();
//                }
//            } elseif (count($document_achat) >= 1 && $contrat->getIdTypedoc() == 20) {
////            if($doc_acha->getId().'mp');
////                $piece_provisoire = Doctrine_Core::getTable('ligavisdoc')->findOneByIdDoc($document_achat->getId());
////
////                if ($piece_provisoire) {
////                    $pie = $piece_provisoire;
////                    return $pie->getLigprotitrub()->getTitreEtRubrique();
////                }
//                $p = new Piecejointbudget();
//                $piece = Doctrine_Core::getTable('piecejointbudget')->findOneByIdDocachat($doc_acha->getId());
//
//                if ($piece) {
//                    $p = $piece;
//                    return $p->getDocumentbudget()->getLigprotitrub()->getTitreEtRubrique();
//                }
//            }
//        }
//        }

        return $html;
    }

    public function ActionSignatureContratDefinitif($iddoc) {
//die($iddoc.'wde');
        $html = "";
        $contra_definitif = ContratachatTable::getInstance()->findOneById($iddoc);
        $doc_achat_contrat_defi = DocumentachatTable::getInstance()->getByidDocAndType($iddoc, 20);


        $p = new Piecejointbudget();
        if (count($doc_achat_contrat_defi) >= 1) {
            $piece = Doctrine_Core::getTable('piecejointbudget')->findOneByIdDocachat($doc_achat_contrat_defi->getFirst()->getId());

            if ($piece) {
                $p = $piece;
                return $p->getDocumentbudget()->getLigprotitrub()->getTitreEtRubrique();
            }
        }
//        if (sizeof($doc_achat_contrat_defi) >= 1) {
////             echo($iddoc. "fre".sizeof($doc_achat_contrat_defi).'fr'.$contra_definitif->getId());
//            $doc_fils_contra = DocumentachatTable::getInstance()->findOneById($doc_achat_contrat_defi->getIdDocparent());
//
//            $doc_achat_contra = DocumentachatTable::getInstance()->find($doc_fils_contra->getIdDocparent());
//        }
////        if (sizeof($doc_achat_contrat_pro) >= 1 && sizeof($doc_achat_contrat_defi) == 1)
////            $doc_achat_contra = DocumentachatTable::getInstance()->findOneById($doc_achat_contrat_pro->getIdDocparent());
//
//        $lg = new ligavisdoc();
//
//        if (sizeof($doc_achat_contra) >= 1) {
//            $piece_provisoire = Doctrine_Core::getTable('ligavisdoc')->findOneByIdDoc($this->getDocumentachat()->getFirst()->getId());
//            $p = new Piecejointbudget();
//            $piece = Doctrine_Core::getTable('piecejointbudget')->findOneByIdDocachat($this->getDocumentachat()->getFirst()->getId());
////        die($piece->getId() . 'rt');
//            if ($piece) {
//                $p = $piece;
//                return $p->getDocumentbudget()->getLigprotitrub()->getTitreEtRubrique();
//            }
//            if ($piece_provisoire) {
//                $pie = $piece_provisoire;
//                return $pie->getLigprotitrub()->getTitreEtRubrique();
//            }
//        }
//        }

        return $html;
    }

      public function ReadHtmlContratFAc($listesdocuments,$contratachat) {
      
        $html = '';
        $fournisseur = new Fournisseur();
        $frs = Doctrine_Core::getTable('fournisseur')->findOneById($contratachat->getIdFrs());
        $fournisseur = $frs;
        if ($contratachat->getIdTypedoc() == 19) {
            $type = 'Provisoire';
        } else if ($contratachat->getIdTypedoc() == 20) {
            $type = 'Définitif';
        }

        $html.= '<div class="contenue">' .
                '<div class="titre"><h3> Fiche contrat ' . ' N°: ' . $contratachat->getNumero() . '</h3></div>
                <div>
                    <table style="width:100%;">';

        $html.='<tr>'
                . '<td style="font-size:12px;font-weight:bold;">Nom du contrat</td>'
                . '<td><label>' . $contratachat->getReference();
        $html.= '</label></td>
                    </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Fournisseur</td>
                    <td style="font-size:12px;font-weight:bold;"><h6>' . $fournisseur->getRs() . '</h6></td>
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date création</td>
                    <td><h6>' . date('d/m/Y', strtotime($contratachat->getDatecreation())) . '</h6></td> 
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date Signature</td>
                    <td><h6>' . date('d/m/Y', strtotime($contratachat->getDatesigntaure())) . '</h6></td> 
                </tr>';
        $html.= '<tr><td style="font-size:12px;font-weight:bold;">Montant Contrat</td><td>' .
                number_format($contratachat->getMontantcontrat(), 3, ".", " ") . '</td>'
                . '</tr>';

        $html.= '</table>
                </div>';
        $html.='<div>
             <legend><h6>Liste des articles du contrat</h6></legend>
           <br> <table class="tableligne" style="width:100%;">
            <tr style="background-color:#EDEDED;font-size:14px;">
                <th style="width: 5%">N°</th>
                    <th style="text-align:center;width: 15%">Désigntation</th>
                    <th style="width:7%">Unité</th>
                    <th style="width: 7%">Qte</th>
                     <th style="width: 12%">T.H.Tax</th>
                    <th style="width: 12%" class="disabledbutton">T.H.TVA</th>
                    <th style="width: 8%" class="disabledbutton">Taux<br>T.V.A</th>
                    <th style="width: 12%" class="disabledbutton">T.TTC</th>
                    <th style="width: 22%">Projet & Observations</th>';
        $html.='</tr>             
        <tbody>';
        $lg = new Lignecontrat();
        $i = 0;
        $class = "secondtd";
        foreach ($listesdocuments as $lignedoc) {
            $var = $i % 2;
            // die($var.'hh');
            if ($var == 0)
                $class = "fersttd";
            else
                $class = "secondtd";
            $i++;
            $lg = $lignedoc;

            $html.=' <tr class="font-size:12px; ' . $class . '">
                <td>' . sprintf('%02d', $lg->getNordre()) . '</td>
                <td style="text-align:left;">' . $lg->getDesignationartcile() . '</td>';
            $html.='   <td>';
            if ($lg->getIdUnitemarche() != 51)
                $html.= $lg->getUnitemarche();
            $html.='</td>';
            $html.='   <td>' . intval($lg->getQte()) . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntht(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntthtva(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . $lg->getTva() . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntttc(), 3, '.', ' ') . '</td><td>';
            if ($lg->getIdProjet())
                $html .= 'Projet:' . $lg->getProjet() . '<br >';
            if ($lg->getObservation() && $lg->getObservation() != "")
                $html.='Observation: ' . $lg->getObservation();
            $html.= '</td>';

            $html.=' </tr>';
            $liste_ligne_contrat = Doctrine_Core::getTable('lignecontrat')->findByIdDocparent($lg->getId());
        }
        $html.='</tbody></table></div></div>';
        $html.= '<div>
            <table>
      <tr>';

        $html.='</tr></table>
            </div>';
        if (count($liste_ligne_contrat) >= 1):
            $html.='<table>
                    <legend>Sous détail du Ligne de contrat</legend>
                    <thead>
                    <th>N°Ordre</th>
                    <th>Designatioon Article</th>
                    <th>Type Pièce </th>
                    <th>Taux de Pourcentage</th>
                    </thead>
                    <tbody>';
            foreach ($liste_ligne_contrat as $ligne_lg) {
                $html.='       <tr>
                                <td>' . sprintf('%02d', $ligne_lg->getNordre() + 1) . '</td>

                                <td>' . $ligne_lg->getDesignationartcile() . '</td>
                                <td >' . $ligne_lg->getTypepiececontrat()->getLibelle() . '</td>
                                <td style="text-align: right">'
                        . $ligne_lg->getTauxpourcentage() . ' %' . '</td></tr> ';
            }

            $html.='</tbody></table>';
            $html.='</div>';
        endif;
        return $html;
    }

    public function ReadHtmlContrat($listesdocuments) {
//        die($this->getId());
        $html = '';
        $fournisseur = new Fournisseur();
        $frs = Doctrine_Core::getTable('fournisseur')->findOneById($this->getIdFrs());
        $fournisseur = $frs;
        if ($this->getIdTypedoc() == 19) {
            $type = 'Provisoire';
        } else if ($this->getIdTypedoc() == 20) {
            $type = 'Définitif';
        }

        $html.= '<div class="contenue">' .
                '<div class="titre"><h3> Fiche contrat ' . ' N°: ' . $this->getNumero() . '</h3></div>
                <div>
                    <table style="width:100%;">';

        $html.='<tr>'
                . '<td style="font-size:12px;font-weight:bold;">Nom du contrat</td>'
                . '<td>' . $this->getReference();
        $html.= '</h6></td>
                    </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Fournisseur</td>
                    <td style="font-size:12px;font-weight:bold;"><h6>' . $fournisseur->getRs() . '</h6></td>
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date création</td>
                    <td><h6>' . date('d/m/Y', strtotime($this->getDatecreation())) . '</h6></td> 
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date Signature</td>
                    <td><h6>' . date('d/m/Y', strtotime($this->getDatesigntaure())) . '</h6></td> 
                </tr>';
        $html.= '<tr><td style="font-size:12px;font-weight:bold;">Montant Contrat</td><td>' .
                number_format($this->getMontantcontrat(), 3, ".", " ") . '</td>'
                . '</tr>';

        $html.= '</table>
                </div>';
        $html.='<div>
             <legend>Liste des articles du contrat</legend>
            <table class="tableligne" style="width:100%;">
            <tr style="background-color:#EDEDED;font-size:14px;">
                <th style="width: 5%">N°</th>
                    <th style="text-align:center;width: 15%">Désigntation</th>
                    <th style="width:7%">Unité</th>
                    <th style="width: 7%">Qte</th>
                     <th style="width: 12%">T.H.Tax</th>
                    <th style="width: 12%" class="disabledbutton">T.H.TVA</th>
                    <th style="width: 8%" class="disabledbutton">Taux<br>T.V.A</th>
                    <th style="width: 12%" class="disabledbutton">T.TTC</th>
                    <th style="width: 22%">Projet & Observations</th>';
        $html.='</tr>             
        <tbody>';
        $lg = new Lignecontrat();
        $i = 0;
        $class = "secondtd";
        foreach ($listesdocuments as $lignedoc) {
            $var = $i % 2;
            // die($var.'hh');
            if ($var == 0)
                $class = "fersttd";
            else
                $class = "secondtd";
            $i++;
            $lg = $lignedoc;

            $html.=' <tr class="font-size:12px; ' . $class . '">
                <td>' . sprintf('%02d', $lg->getNordre()) . '</td>
                <td style="text-align:left;">' . $lg->getDesignationartcile() . '</td>';
            $html.='   <td>';
            if ($lg->getIdUnitemarche() != 51)
                $html.= $lg->getUnitemarche();
            $html.='</td>';
            $html.='   <td>' . intval($lg->getQte()) . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntht(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntthtva(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . $lg->getTva() . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntttc(), 3, '.', ' ') . '</td><td>';
            if ($lg->getIdProjet())
                $html .= 'Projet:' . $lg->getProjet() . '<br >';
            if ($lg->getObservation() && $lg->getObservation() != "")
                $html.='Observation: ' . $lg->getObservation();
            $html.= '</td>';

            $html.=' </tr>';
            $liste_ligne_contrat = Doctrine_Core::getTable('lignecontrat')->findByIdDocparent($lg->getId());
        }
        $html.='</tbody></table></div></div>';
        $html.= '<div>
            <table>
      <tr>';

        $html.='</tr></table>
            </div>';
        if (count($liste_ligne_contrat) >= 1):
            $html.='<table>
                    <legend>Sous détail du Ligne de contrat</legend>
                    <thead>
                    <th>N°Ordre</th>
                    <th>Designatioon Article</th>
                    <th>Type Pièce </th>
                    <th>Taux de Pourcentage</th>
                    </thead>
                    <tbody>';
            foreach ($liste_ligne_contrat as $ligne_lg) {
                $html.='       <tr>
                                <td>' . sprintf('%02d', $ligne_lg->getNordre() + 1) . '</td>

                                <td>' . $ligne_lg->getDesignationartcile() . '</td>
                                <td >' . $ligne_lg->getTypepiececontrat()->getLibelle() . '</td>
                                <td style="text-align: right">'
                        . $ligne_lg->getTauxpourcentage() . ' %' . '</td></tr> ';
            }

            $html.='</tbody></table>';
            $html.='</div>';
        endif;
        return $html;
    }

    public function ReadHtmlcontratProvisoire($iddoc) {
        $contrat_definitif = ContratachatTable::getInstance()->find($iddoc);
        $listesdocuments = Doctrine_Core::getTable('lignecontrat')
                        ->createQuery('a')
                        ->where('id_contrat=' . $iddoc)
                        ->orderBy('id asc')->execute();
        $html = '';
        $fournisseur = new Fournisseur();
        $frs = Doctrine_Core::getTable('fournisseur')->findOneById($contrat_definitif->getIdFrs());
        $fournisseur = $frs;
        $type = '';
        if ($contrat_definitif->getIdTypedoc() == 19) {
            $type = 'Provisoire';
        } else if ($this->getIdTypedoc() == 20) {
            $type = 'Définitif';
        }
        $html.= '<div class="contenue">' .
                '<div class="titre"><h3> Fiche contrat  ' . $type
                . '</h3></div>
                <div>
                    <table style="width:100%;">';

        $html.='<tr>'
                . '<td style="font-size:12px;font-weight:bold;">N° du contrat</td>'
                . '<td><h6>' . $contrat_definitif->getNumero();
        $html.= '</h6></td>
                    </tr>';
        $html.='<tr>'
                . '<td style="font-size:12px;font-weight:bold;">Nom du contrat</td>'
                . '<td>' . $contrat_definitif->getReference()
        ;
        $html.= '</td>
                    </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Fournisseur</td>
                    <td style="font-size:12px;font-weight:bold;"><h6>' . $fournisseur->getRs() . '</h6></td>
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date création</td>
                    <td><h6>' . date('d/m/Y', strtotime($contrat_definitif->getDatecreation())) . '</h6></td> 
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date Signature</td>
                    <td><h6>' . date('d/m/Y', strtotime($contrat_definitif->getDatesigntaure())) . '</h6></td> 
                </tr>';
        $html.= '<tr><td style="font-size:12px;font-weight:bold;">Montant Contrat</td><td><h6>' .
                number_format($contrat_definitif->getMontantcontrat(), 3, ".", " ") . '</h6></td>'
                . '</tr>';

        $html.= '</table>
                </div>';
        $html.='<div class="titre"><h3> Liste des Articles  </h3></div>
              <div> 
            <table class="tableligne" style="width:100%;">
            <tr style="background-color:#EDEDED;font-size:14px;">
                <th style="width: 5%">N°</th>
                    <th style="text-align:center;width: 31%">Désigntation</th>
                    <th style="width:7%">Unité</th>
                    <th style="width: 7%">Qte</th>
                     <th style="width: 12%">T.H.Tax</th>
                    <th style="width: 15%" class="disabledbutton">T.H.TVA</th>
                    <th style="width: 8%" class="disabledbutton">Taux<br>T.V.A</th>
                    <th style="width: 15%" class="disabledbutton">T.TTC</th>';
//                    <th style="width: 22%">Projet & Observations</th>';
        $html.='</tr>             
        <tbody>';
        $lg = new Lignecontrat();
        $i = 0;
        $class = "secondtd";
        foreach ($listesdocuments as $lignedoc) {
            $var = $i % 2;
            // die($var.'hh');
            if ($var == 0)
                $class = "fersttd";
            else
                $class = "secondtd";
            $i++;
            $lg = $lignedoc;

            $html.=' <tr class="font-size:12px; ' . $class . '">
                <td>' . sprintf('%02d', $lg->getNordre()) . '</td>
                <td style="text-align:left;">' . $lg->getDesignationartcile() . '</td>';
            $html.='   <td>' . $lg->getUnitemarche() . '</td>';
            $html.='   <td>' . intval($lg->getQte()) . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntht(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntthtva(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . $lg->getTva() . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntttc(), 3, '.', ' ') . '</td>';
//          $html.= '<td>';
//            if ($lg->getIdProjet())
//                $html .= 'Projet:' . $lg->getProjet() . '<br >';
//            if ($lg->getObservation() && $lg->getObservation() != "")
//                $html.='Observation: ' . $lg->getObservation();
//            $html.= '</td>';

            $html.=' </tr>';
            $liste_ligne_contrat = Doctrine_Core::getTable('lignecontrat')->findByIdDocparent($lg->getId());
        }
        $html.='</tbody></table></div></div>';
        $html.= '<div>
            <table><tr>';
        $html.='</tr></table>
            ';
        if (count($liste_ligne_contrat) >= 1):
            $html.='<div class="titre"><h3>Sous détail du Ligne de contrat </h3></div> 
     
    <table class="tableligne" style="width:100%;">
                   
                    <tr style="background-color:#EDEDED;font-size:14px;"> 
                    <th>N°Ordre</th>
                    <th>Designatioon Article</th>
                    <th>Type Pièce </th>
                    <th>Taux de Pourcentage</th>
                   </tr>
                    <tbody>';
            foreach ($liste_ligne_contrat as $ligne_lg) {
                $html.='       <tr>
                                <td>' . sprintf('%02d', $ligne_lg->getNordre() + 1) . '</td>

                                <td>' . $ligne_lg->getDesignationartcile() . '</td>
                                <td >' . $ligne_lg->getTypepiececontrat()->getLibelle() . '</td>
                                <td style="text-align: right">'
                        . $ligne_lg->getTauxpourcentage() . ' %' . '</td></tr> ';
            }

            $html.='</tbody></table></div>';
        endif;
        return $html;
    }

    public function ReadHtmlcontratdefintif($iddoc) {
        $contrat_definitif = ContratachatTable::getInstance()->find($iddoc);
        $listesdocuments = Doctrine_Core::getTable('lignecontrat')
                        ->createQuery('a')
                        ->where('id_contrat=' . $iddoc)
                        ->orderBy('id asc')->execute();
        $html = '';
        $fournisseur = new Fournisseur();
        $frs = Doctrine_Core::getTable('fournisseur')->findOneById($contrat_definitif->getIdFrs());
        $fournisseur = $frs;
        $type = '';
        if ($contrat_definitif->getIdTypedoc() == 19) {
            $type = 'Provisoire';
        } else if ($this->getIdTypedoc() == 20) {
            $type = 'Définitif';
        }
        $html.= '<div class="contenue">' .
                '<div class="titre"><h3> Fiche contrat  ' . $type
                . '</h3></div>
                <div>
                    <table style="width:100%;">';

        $html.='<tr>'
                . '<td style="font-size:12px;font-weight:bold;">N° du contrat</td>'
                . '<td><h6>' . $contrat_definitif->getNumero();
        $html.= '</h6></td>
                    </tr>';
        $html.='<tr>'
                . '<td style="font-size:12px;font-weight:bold;">Nom du contrat</td>'
                . '<td>' . $contrat_definitif->getReference()
        ;
        $html.= '</td>
                    </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Fournisseur</td>
                    <td style="font-size:12px;font-weight:bold;"><h6>' . $fournisseur->getRs() . '</h6></td>
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date création</td>
                    <td><h6>' . date('d/m/Y', strtotime($contrat_definitif->getDatecreation())) . '</h6></td> 
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;font-weight:bold;">Date Signature</td>
                    <td><h6>' . date('d/m/Y', strtotime($contrat_definitif->getDatesigntaure())) . '</h6></td> 
                </tr>';
        $html.= '<tr><td style="font-size:12px;font-weight:bold;">Montant Contrat</td><td><h6>' .
                number_format($contrat_definitif->getMontantcontrat(), 3, ".", " ") . '</h6></td>'
                . '</tr>';

        $html.= '</table>
                </div>';
        $html.='<div class="titre"><h3> Liste des Articles  </h3></div>
              <div> 
            <table class="tableligne" style="width:100%;">
            <tr style="background-color:#EDEDED;font-size:14px;">
                <th style="width: 5%">N°</th>
                    <th style="text-align:center;width: 15%">Désigntation</th>
                    <th style="width:7%">Unité</th>
                    <th style="width: 7%">Qte</th>
                     <th style="width: 12%">T.H.Tax</th>
                    <th style="width: 12%" class="disabledbutton">T.H.TVA</th>
                    <th style="width: 8%" class="disabledbutton">Taux<br>T.V.A</th>
                    <th style="width: 12%" class="disabledbutton">T.TTC</th>
                    <th style="width: 22%">Projet & Observations</th>';
        $html.='</tr>             
        <tbody>';
        $lg = new Lignecontrat();
        $i = 0;
        $class = "secondtd";
        foreach ($listesdocuments as $lignedoc) {
            $var = $i % 2;
            // die($var.'hh');
            if ($var == 0)
                $class = "fersttd";
            else
                $class = "secondtd";
            $i++;
            $lg = $lignedoc;

            $html.=' <tr class="font-size:12px; ' . $class . '">
                <td>' . sprintf('%02d', $lg->getNordre()) . '</td>
                <td style="text-align:left;">' . $lg->getDesignationartcile() . '</td>';
            $html.='   <td>';
            if ($lg->getIdUnitemarche() != 51)
                $html.= $lg->getUnitemarche();
            $html.=' </td>';
            $html.='   <td>' . intval($lg->getQte()) . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntht(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntthtva(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . $lg->getTva() . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntttc(), 3, '.', ' ') . '</td><td>';
            if ($lg->getIdProjet())
                $html .= 'Projet:' . $lg->getProjet() . '<br >';
            if ($lg->getObservation() && $lg->getObservation() != "")
                $html.='Observation: ' . $lg->getObservation();
            $html.= '</td>';

            $html.=' </tr>';
            $liste_ligne_contrat = Doctrine_Core::getTable('lignecontrat')->findByIdDocparent($lg->getId());
        }
        $html.='</tbody></table></div></div>';
        $html.= '<div>
            <table><tr>';
        $html.='</tr></table>
            ';
        if (sizeof($liste_ligne_contrat) > 0) {
            $html.='<div class="titre"><h3>Sous détail du Ligne de contrat </h3></div> 
     
    <table class="tableligne" style="width:100%;">
                   
                    <tr style="background-color:#EDEDED;font-size:14px;"> 
                    <th>N°Ordre</th>
                    <th>Designatioon Article</th>
                    <th>Type Pièce </th>
                    <th>Taux de Pourcentage</th>
                   </tr>
                    <tbody>';
            foreach ($liste_ligne_contrat as $ligne_lg) {
                $html.='       <tr>
                                <td>' . sprintf('%02d', $ligne_lg->getNordre() + 1) . '</td>

                                <td>' . $ligne_lg->getDesignationartcile() . '</td>
                                <td >' . $ligne_lg->getTypepiececontrat()->getLibelle() . '</td>
                                <td style="text-align: right">'
                        . $ligne_lg->getTauxpourcentage() . ' %' . '</td></tr> ';
            }

            $html.='</tbody></table></div>';
        }
        return $html;
    }

    public function ReadHtmlcontratdefintifAvecPenalite($iddoc, $iddocacht) {
        $contrat_definitif = ContratachatTable::getInstance()->find($iddoc);
        $listesdocuments = Doctrine_Core::getTable('lignecontrat')
                        ->createQuery('a')
                        ->where('id_contrat=' . $iddoc)
                        ->orderBy('id asc')->execute();
        $html = '';
        $fournisseur = new Fournisseur();
        $frs = Doctrine_Core::getTable('fournisseur')->findOneById($contrat_definitif->getIdFrs());
        $fournisseur = $frs;
        $html.= '<div class="contenue">' .
                '<div class="titre"><h3> Fiche contrat '
                //  . $contrat_definitif->getNumero()  
                . '</h3></div>
                <div>
                    <table style="width:100%;" class="tableligne" border="1" >';
        $html.='<tr>'
                . '<td style="font-size:12px;">N° du contrat</td>'
                . '<td>' . $contrat_definitif->getNumero();
        $html.= '</td>';
        $html.='<td style="font-size:12px;">Nom du contrat</td>'
                . '<td>' . $contrat_definitif->getReference()
        ;
        $html.= '</td>
                    </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;">Fournisseur</td>
                    <td style="font-size:12px;">' . $fournisseur->getRs() . '</td>
                ';
        $html.= ' <td style="font-size:12px;">Date création</td>
                    <td>' . date('d/m/Y', strtotime($contrat_definitif->getDatecreation())) . '</td> 
                </tr>';
        $html.= '<tr>
                    <td style="font-size:12px;">Date Signature</td>
                    <td>' . date('d/m/Y', strtotime($contrat_definitif->getDatesigntaure())) . '</td> 
                ';
        $html.= ' <td style="font-size:12px;">Date Fin</td>
                    <td>' . date('d/m/Y', strtotime($contrat_definitif->getDatefin())) . '</td>'
                . '</tr>';


        $html.= '<tr>'
                . '<td style="font-size:12px;">Montant Contrat</td><td>' .
                number_format($contrat_definitif->getMontantcontrat(), 3, ".", " ") . '</td>';

        $html.= '<td style="font-size:12px;">Cautionnement définitif %</td><td>' .
                $contrat_definitif->getCautionement() . '</td>';


        $html.= '</tr>';

        $html.= '<tr>'
                . '<td style="font-size:12px;">Retenue de garantie%</td><td>' .
                $contrat_definitif->getRetenuegaraentie() . '</td>';

        $html.= '<td style="font-size:12px;">Avance%</td><td>' .
                $contrat_definitif->getAvance() . '</td>';


        $html.= '</tr>';


        $html.= '<tr>'
                . '<td style="font-size:12px;">Pénalité de RETARD%/Jour</td><td>' .
                $contrat_definitif->getPenalite() . '</td>';

        $html.= '<td style="font-size:12px;">Max Pénalité de RETARD</td><td>' .
                $contrat_definitif->getMaxpinalite() . '</td>';


        $html.= '</tr>';
        $html.= '</table>
                </div>';
        $html.='
             <h4><span style="color:#000; font-size:16px;">Liste des Articles  :</span></h4>
            
              <div> 
            <table class="tableligne" style="width:100%;">
            <tr style="background-color:#EDEDED;font-size:14px;">
                <th style="width: 5%">N°</th>
                    <th style="text-align:center;width: 15%">Désigntation</th>
                    <th style="width:9%">Unité</th>
                    <th style="width: 5%">Qte</th>
                     <th style="width: 14%">T.H.Tax</th>
                    <th style="width: 14%" class="disabledbutton">T.H.TVA</th>
                    <th style="width: 8%" class="disabledbutton">Taux<br>T.V.A</th>
                    <th style="width: 14%" class="disabledbutton">T.TTC</th>
                    <th style="width: 15%">Projet & Observations</th>';
        $html.='</tr>             
        <tbody>';
        $lg = new Lignecontrat();
        $i = 0;
        $class = "secondtd";
        foreach ($listesdocuments as $lignedoc) {
            $var = $i % 2;
            // die($var.'hh');
            if ($var == 0)
                $class = "fersttd";
            else
                $class = "secondtd";
            $i++;
            $lg = $lignedoc;
            //' . $class . '//
            $html.=' <tr class="font-size:12px;">
                <td>' . sprintf('%02d', $lg->getNordre()) . '</td>
                <td style="text-align:left;">' . $lg->getDesignationartcile() . '</td>';
            $html.='   <td>' . $lg->getUnitemarche() . '</td>';
            $html.='   <td>' . intval($lg->getQte()) . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntht(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntthtva(), 3, '.', ' ') . '</td>';
            $html.='<td style="text-align:center;">' . $lg->getTva() . '</td>';
            $html.='<td style="text-align:center;">' . number_format($lg->getMntttc(), 3, '.', ' ') . '</td><td>';
            if ($lg->getIdProjet())
                $html .= $lg->getProjet() . '<br>';
            if ($lg->getObservation() && $lg->getObservation() != "")
                $html.='&' . $lg->getObservation();
            $html.= '</td>';

            $html.=' </tr>';
            $liste_ligne_contrat = Doctrine_Core::getTable('lignecontrat')->findByIdDocparent($lg->getId());
        }
        $html.='</tbody></table></div></div>';
        $html.= '<div>';
        if (sizeof($liste_ligne_contrat) >= 1):
            $html.='<div class="titre"><h3>Sous détail du Ligne de contrat </h3></div> 
     
    <table class="tableligne" style="width:100%;">
                   
                    <tr style="background-color:#EDEDED;font-size:14px;"> 
                    <th>N°Ordre</th>
                    <th>Designatioon Article</th>
                    <th>Type Pièce </th>
                    <th>Taux de Pourcentage</th>
                   </tr>
                    <tbody>';
            foreach ($liste_ligne_contrat as $ligne_lg) {
                $html.='       <tr>
                                <td>' . sprintf('%02d', $ligne_lg->getNordre() + 1) . '</td>

                                <td>' . $ligne_lg->getDesignationartcile() . '</td>
                                <td >' . $ligne_lg->getTypepiececontrat()->getLibelle() . '</td>
                                <td style="text-align: right">'
                        . $ligne_lg->getTauxpourcentage() . ' %' . '</td></tr> ';
            }

            $html.='</tbody></table>';
        endif;
        $html.='<div>
            <h4><span style="color:#000; font-size:16px;">Liste des O.S :</span></h4>';
        $html.='<table class="tableligne" style="width:100%;font-size:10px;">
                <tr style="background-color:#DEDEDE;">
                    <th style="width:10%">N°</th>
                    <th style="width: 20%">Type OS</th>
                    <th style="width: 25%">Date Commencement</th>
                    <th style="width: 45%">Objet</th>
                </tr>
                <tbody>';
//
        $OSS = Doctrine_Core::getTable('ordredeservicecontratachat')
                        ->createQuery('a')->where('id_contrat=' . $iddoc)
                        ->andwhere('id_type in (1,4,5,6)')
                        ->orderBy('id asc')->execute();

        $ordres = new Ordredeservicecontratachat();
        $i = 0;
        foreach ($OSS as $odsss) {
            $ordres = $odsss;
            $i++;
            $dateaction = "";
            $color = "";
            if ($ordres->getIdType() == "1") {
                $dateaction = "Commencement";
                $color = "#000";
            } elseif ($ordres->getIdType() == "4") {
                $dateaction = "Arrêt";
                $color = "red";
            } elseif ($ordres->getIdType() == "5") {
                $dateaction = "Reprise";
                $color = "green";
            } elseif ($ordres->getIdType() == "6") {
                $dateaction = 'Divers';
                $color = "blue";
            }
            $html.='<tr>
                            <td style="text-align:center;"><span style="color:#000">' . $i . '</span></td>
                            <td style="text-align:center;"><span style="color:#000">' . $ordres->getTypeios() . '</span></td>
                            <td style="text-align:center;"><span style="color:' . $color . '">' . $dateaction . ' : ' . date('d/m/Y', strtotime($ordres->getDateios())) . '</span></td>
                            <td style="text-align:left;"><span style="color:#000">' . $ordres->getObject() . '</span></td>
                        </tr>';
        }

        $html.='</tbody>
                </table>
                </div>';
        $html.= '</div>';
        return $html;
    }

    public function ReadHtmlTableOs($id, $idcontrat) {
        $doc_achat = DocumentachatTable::getInstance()->find($id);
        $contratachat = ContratachatTable::getInstance()->find($idcontrat);


        $html = '<div class="titre"><h3 style="font-size:18px;">Liste des O.S - Bénéficiaire : '
                . $contratachat->getFournisseur() . '<br>Contrat : ' . $contratachat->getReference() . ' - Projet : '
                . $doc_achat->getProjet() . '</h3></div>&nbsp;<br>';

        $html.='<h4><span style="color:#000; font-size:16px;">Fiche Bénéficiaire :</span></h4>
                <h5><span style="color:#000; font-size:14px;">Information Bénéficiaire : '
                . $contratachat->getFournisseur() . '</span></h5>
                <table class="tableligne" style="width:100%; font-size:12px;">
                    <tbody>
                        <tr><td><label>Fournisseur</label></td>
                        <td colspan="5">' . $contratachat->getFournisseur() . ' </td> </tr>
                        <tr><td><label>Contrat </label></td>
                        <td colspan="2">' . $contratachat->getReference()
                . '   N°: ' . $contratachat->getNumero() . ' </td>
                        <td><label>Document achat </label></td>
                        <td colspan="2">' . $doc_achat->getNumerodocumentachat() . '</td></tr>
                        <tr>
                        <td>Date de création</td>
                        <td style="text-align: cenetr" colspan="2">' . date('d/m/Y', strtotime($contratachat->getDatecreation())) . '</td>
                        <td>Date de Signature</td>
                        <td style="text-align: cenetr" colspan="2">';
        if ($contratachat->getDatesigntaure()):
            $html.= date('d/m/Y', strtotime($contratachat->getDatesigntaure()));
        endif;
        $html.='</td></tr><tr><td>Type</td> <td colspan="2" >';

        if ($contratachat->getType() == 0)
            $html.= 'Livraison Total ';
        else
            $html.= 'Livraison Partiel';
        $html.='</td><td>Date Fin</td><td colspan="2">';
        if ($contratachat->getDatefin()):

            $html.= date('d/m/Y', strtotime($contratachat->getDatefin()));
        endif;

        $html.='</td> </tr>
                    </tbody>
                </table>';

        $html.='<div>
            <h4><span style="color:#000; font-size:16px;">Liste des O.S :</span></h4>';
        $html.='<table class="tableligne" style="width:100%;font-size:10px;">
                <tr style="background-color:#DEDEDE;">
                    <th style="width:65px;">N°</th>
                    <th style="width:200px;">Type OS</th>
                    <th style="width:181px;">Date Commencement</th>
                    <th style="width:500px;">Objet</th>
                </tr>
                <tbody>';
//
        $OSS = Doctrine_Core::getTable('ordredeservicecontratachat')
                        ->createQuery('a')->where('id_contrat=' . $idcontrat)
                        ->andwhere('id_type in (1,4,5,6)')
                        ->orderBy('id asc')->execute();

        $ordres = new Ordredeservicecontratachat();
        $i = 0;
        foreach ($OSS as $odsss) {
            $ordres = $odsss;
            $i++;
            $dateaction = "";
            $color = "";
            if ($ordres->getIdType() == "1") {
                $dateaction = "Commencement";
                $color = "#000";
            } elseif ($ordres->getIdType() == "4") {
                $dateaction = "Arrêt";
                $color = "red";
            } elseif ($ordres->getIdType() == "5") {
                $dateaction = "Reprise";
                $color = "green";
            } elseif ($ordres->getIdType() == "6") {
                $dateaction = 'Divers';
                $color = "blue";
            }
            $html.='<tr>
                            <td style="text-align:center;"><span style="color:#000">' . $i . '</span></td>
                            <td style="text-align:center;"><span style="color:#000">' . $ordres->getTypeios() . '</span></td>
                            <td style="text-align:center;"><span style="color:' . $color . '">' . $dateaction . ' : ' . date('d/m/Y', strtotime($ordres->getDateios())) . '</span></td>
                            <td style="text-align:left;"><span style="color:#000">' . $ordres->getObject() . '</span></td>
                        </tr>';
        }

        $html.='</tbody>
                </table>
                </div>';

        return $html;
    }

    public function MisajourDelaiArretJustfier($ordre) {
        $delai_arret = 0;
        if ($this->getPeriodejustifier() && $this->getPeriodejustifier() != "")
            $delai_arret = intval($this->getPeriodejustifier());
        $osarret = Doctrine_Core::getTable('ordredeservicecontratachat')
                        ->createQuery('a')
                        ->where('id_contrat=' . $ordre->getIdContrat())
                        ->andwhere('id_type=4')
                        ->orderBy('id asc')->execute();
        if (count($osarret) > 0) {
            $date_arret = $osarret[count($osarret) - 1]->getDateios();
            $osdate = Doctrine_Query::create()
                            ->select("to_char(dateios::timestamp without time zone - '" . $date_arret . "'::timestamp without time zone, 'dd') as periode")
                            ->from('ordredeservicecontratachat a')
                            ->where('id=' . $ordre->getId())->execute();
            $delai_arret+=intval($osdate[0]['periode']);
            $contratachat = new Contratachat();
            $ben = Doctrine_Core::getTable('contratachat')->findOneById($ordre->getIdContrat());
            $contratachat = $ben;
            $contratachat->setPeriodejustifier($delai_arret);
            if ($contratachat->getDatefin()) {
                $date_fin_ancien = $contratachat->getDatefin();
                $date_fin_nv = date("Y-m-d", strtotime($date_fin_ancien . '+ ' . $delai_arret . ' days'));
                $contratachat->setDatefin($date_fin_nv);
            }

            $contratachat->save();
        }
    }

}
