<?php

/**
 * CorpsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CorpsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CorpsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Corps');
    }
}