<?php

/**
 * CourrierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourrierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourrierTable
     */
    public static function getInstance()
    {
       
        return Doctrine_Core::getTable('Courrier');
    }
   
}