<?php

/**
 * DemandeavanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemandeavanceTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object DemandeavanceTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Demandeavance');
    }

    public function getByIdAgentsAndIdTypeavanceAndAnnee($id_agent, $typeavance, $annee) {
        $query = $this->createQuery('l');
        $query->select('l.*')
                ->from('Demandeavance l')
                ->where('l.id_agents =' . $id_agent)
                ->andWhere('l.id_typeavance =' . $typeavance)
                ->andWhere("l.annee=" . $annee);

        return $query->execute()->getFirst();
    }

    public function getByListeId($ids) {
        $q = $this->createQuery('mv')
                ->whereIn('mv.id_agents', (array) $ids)
                ->orderBy('mv.id_agents')
                ->execute();
        return $q;
    }

    public function getDemande() {

        $query = $this->createQuery('l');
        $query->select('l.*')
                ->from('Demandeavance l')
                ->where("l.mois <= '" . intval(date("m")) . "'")               
                ->orWhere("l.annee <= '" . date("Y") . "'");

        return $query->execute();
    }

}
