<?php

/**
 * EngagementantecedentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EngagementantecedentTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EngagementantecedentTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Engagementantecedent');
    }

    public function getEngagementFirstDegreeByTitre($id_titre, $annee = '') {
        $q = $this->createQuery('e')
                ->select('e.*')
                ->from('Engagementantecedent e')
                ->leftJoin('e.Ligprotitrub l')
                ->where('e.id_titre = ?', $id_titre);
        if ($annee != '') {
            $date_debut = $annee . '-01-01';
            $date_fin = $annee . '-12-31';
            $q = $q->andWhere("e.date >= '" . $date_debut . "'");
            $q = $q->andWhere("e.date <= '" . $date_fin . "'");
        }
        $q = $q->orderBy('e.annee, LENGTH(l.nordre), l.nordre');
        return $q->execute();
    }

}
