<?php

/**
 * GradeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GradeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object GradeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Grade');
    }
    
    public function findByCategorieOrderByLibelle($id_categorie) {
        $query = $this->createQuery('g');
        $query->from('Grade g')
                ->where('g.id_categorie = ' . $id_categorie)
                ->orderBy('g.libelle');
        return $query->execute();
    }

}
