<?php

/**
 * HistoriquepromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoriquepromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoriquepromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Historiquepromotion');
    }
}