<?php

/**
 * HistoriquecontratouvrierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoriquecontratouvrierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoriquecontratouvrierTable
     */
    public static function getInstance(){
        return Doctrine_Core::getTable('Historiquecontratouvrier');
    }
    
    public function getByIds($id_afecation) {//die('id_aff'.$id_afecation);
        $q = $this->createQuery('hco')
                ->where("hco.id in (" . $id_afecation.")")
                ->orderBy('hco.datefoncontrat')
                ->execute();
        return $q;
    }
    public function getLastByIdContrat($id_contrat) {
        $q = $this->createQuery('hco')
                ->where('hco.id_contratouvrier = ' . $id_contrat)
                ->orderBy('hco.datefoncontrat')
                ->execute();
        return $q->getLast();
    }
}