<?php

/**
 * Inventairestock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Inventairestock extends BaseInventairestock {

    public function getNumeroseqfiche() {
        $doc = Doctrine_Query::create()
                        ->select('COALESCE(MAX(numero::integer),0) as numero')
                        ->from('inventairestock a')
                        ->where('id_mag=' . $this->getIdMag())->execute();
        if ($doc[0]['numero'] == 0) {
            $datey = date('y') * 100;
            return sprintf('%05d', $datey + $doc[0]['numero'] + 1);
        } else {
            $datey = 0;
            return sprintf($doc[0]['numero'] + 1);
        }
    }

}
