<?php

/**
 * JournalcentralisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JournalcentralisateurTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object JournalcentralisateurTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Journalcentralisateur');
    }

    public function getByJournalAndExercice($journal_id, $exercice_id) {
        $q = $this->createQuery('j')
                ->where('j.id_journal = ?', $journal_id)
                ->andWhere('j.id_exercice = ?', $exercice_id)
                ->orderBy("j.mois");
        return $q->execute();
    }

    public function InsertJournalCentralisateur($journal_old, $journal_new) {
        $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
        foreach ($journal_old as $old)
            foreach ($journal_new as $new) {

                $centralisateur_old = $this->getInstance()->findByIdJournalAndIdExercice($old->getId(), $old->getIdExercice());
                $centralisateur_new = $this->getInstance()->findByIdJournalAndIdExercice($new->getId(), $new->getIdExercice());
                if (count($centralisateur_new) == 0) {

                    $query_serie = "INSERT INTO public.journalcentralisateur(
	 id_exercice, id_journal, mois, debit, credit)
	select " . $new->getIdExercice() . " as id_exercice, " . $new->getId() . " as id_journal,mois,0,0 from journalcentralisateur	
	where id_exercice=" . $old->getIdExercice() . " and id_journal=" . $old->getId() . ";";
                    $resultat = $conn->fetchAssoc($query_serie);
                }
            }
    }

}
