<?php

/**
 * LignedocumenttransfertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LignedocumenttransfertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return LignedocumenttransfertTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lignedocumenttransfert');
    }
}