<?php

/**
 * Marches
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Marches extends BaseMarches {

    public function __toString() {
        return "MP" . $this->NumeroSeqMarches();
    }

    public function ChangerEtatDocAchat() {
        $iddoc = $this->getIdDocumentachat();
        if ($iddoc) {
            Doctrine_Query::create()
                    ->update('documentachat')
                    ->set('id_etatdoc', '?', 15)
                    ->where('id=' . $iddoc)
                    ->execute();
        }
    }

    public function getNumeromarches() {
        return sprintf('%06d', $this->getNumero());
    }

    public function NumeroSeqMarches() {
        if (!$this->getId()) {
            $doc = Doctrine_Query::create()
                            ->select('COALESCE(MAX(a.numero),0) as numero')
                            ->from('marches a')->execute();
            return sprintf('%06d', $doc[0]['numero']+1);
        } else {
            return sprintf('%06d', $this->getNumero() );
        }
    }

    public function ReadHtmlMarches($id, $user) {

        $marche = MarchesTable::getInstance()->find($id);
        $lots = LotsTable::getInstance()->getByIdMarche($id);
        $societe = Doctrine_Core::getTable('societe')->findOneById(1);

        $html = '<h3 style="font-size:18px;">Fiche Marché ' . 'MP' . $this->NumeroSeqMarches() . ' ' . $marche->getObject() . '</h3>';

        $html.='<h2 style="background-color:#ECECEC;"> Fiche Marché</h2></br>';
        $html.='</br><h4><br>Identification du responsable des marchés Publics</br></h4>';
        $html.='<br><table class="tableligne" style="width:100%; font-size:12px;">
                    <tbody>
                        <tr>
                            <td style="width:30%;text-align:left;"><b>Acheteur Public</b></td>
                            <td style="width:70%;text-align:left;" colspan="3">' . $societe . '</td>
                        </tr>
                        <tr>
                            <td style="width:30%;text-align:left;"><b>Responsable cellule des marchés</b></td>
                            <td style="width:70%;text-align:left;" colspan="3">' . $user . '</td>
                        </tr>
                        <tr>
                            <td style="width:30%;text-align:left;"><b>Tél</b></td>
                            <td style="width:25%;">' . $societe->getTel() . '</td>
                            <td style="width:20%;text-align:left;"><b>Fax</b></td>
                            <td style="width:25%;">' . $societe->getFax() . '</td>
                        </tr>
                        <tr>
                            <td style="width:30%;text-align:left;"><b>E-mail</b></td>
                            <td style="width:70%;text-align:left;" colspan="3">' . $societe->getMail() . '</td>
                        </tr>
                    </tbody>
                </table>&nbsp;<br>';

        $html.='<h4>Informations sur le marché</h4>';
        $html.='<table class="tableligne" style="width:100%; font-size:12px;">
                    <tbody>
                        <tr>
                            <td colspan="2" style="text-align:left;"><b>Bon de commande interne Marchés Public</b></td>
                            <td>' . $marche->getDocumentachat() . '</td>
                            <td style="text-align:left;"><b>Projet</b></td>
                            <td colspan="2" style="text-align:left;">' . $marche->getProjet() . '</td>
                        </tr>
                        <tr>
                            <td style="text-align:left;"><b>Fournisseur</b></td>
                            <td colspan="5">' . $marche->getFournisseur() . '</td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align:left;"><b>date création fiche marché</b></td>
                            <td>' . $marche->getDatecreation() . '</td>
                            <td style="text-align:left;"><b>Numéro fiche marché</b></td>
                            <td colspan="2">' . $marche->getNumero() . '</td>
                        </tr>
                        <tr>
                            <td style="text-align:left;"><b>Nature du Marché</b></td>
                            <td colspan="2">' . $marche->getNaturemarche() . '</td>
                            <td colspan="2" style="text-align:left;"><b>Délai contractuel (Délai par Jour)</b></td>
                            <td>' . $marche->getDelai() . '</td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align:left;"><b>Procédure de passation</b></td>
                            <td colspan="4" style="text-align:left;">' . $marche->getProcedurepassation() . '</td>
                        </tr>
                        <tr>
                            <td colspan="2" style="text-align:left;"><b>Marché réservé au PME</b></td>
                            <td>' . $marche->getMrpme() . '</td>
                            <td colspan="2" style="text-align:left;"><b>Nombre de Lots</b></td>
                             <td >';
        if ($marche->getNbrelot())
            $html.=$marche->getNbrelot();
        else
            $html.='1';
        $html.='</td>';

        //style="background-color:#ECECEC;"
        $html.=' </tr>
                        <tr >
                            <td style="text-align:left;"><b>Titulaire du marché</b></td>
                            <td colspan="2">' . $marche->getTitulaire() . '</td>
                            <td colspan="2" style="text-align:left;"><b>Nombre de Bénificiaires</b></td>
                            <td>' . $marche->getNbrebinificaire() . '</td>
                        </tr>
                        <tr>
                            <td style="text-align:left;"><b>Objet du Marché</b></td>
                            <td colspan="6" style="text-align:left; height:50px;">' . $marche->getObject() . '</td>
                        </tr>
                    </tbody>
                </table>&nbsp;<br>';

        $html.='<table class="tableligne" style="width:100%; font-size:12px;">
                    <tbody>
                        <tr>
                            <td style="width:17%;text-align:left;"><b>Montant Global TTC</b></td>
                            <td colspan="5" style="width:83%;text-align:left;">' . $marche->getMntttc() . '</td>
                        </tr>
                        <tr>
                            <td colspan="2" style="width:28%;text-align:left;"><b>Cautionnement définitif en %</b></td>
                            <td style="width:25%;">' . $marche->getCautionement() . '</td>
                            <td colspan="2" style="width:36%;text-align:left;"><b>Retenue de garantie en %</b></td>
                            <td style="width:11%;">' . $marche->getRetenuegaraentie() . '</td>
                        </tr>
                        <tr>
                            <td style="width:17%; text-align:left;"><b>Avance en %</b></td>
                            <td style="width:11%;">' . $marche->getAvance() . '</td>
                            <td style="width:25%;text-align:left;"><b>Pénalité de RETARD en %/Jour</b></td>
                            <td style="width:11%;">' . $marche->getPenalite() . '</td>
                            <td style="width:25%;text-align:left;"><b>Max Pénalité de RETARD en %</b></td>
                            <td style="width:11%;">' . $marche->getMaxpinalite() . '</td>
                        </tr>
                    </tbody>
                </table>&nbsp;<br><br>';

        $document_achat = $marche->getDocumentachat();
        $aviss = Doctrine_Core::getTable('avis')
                        ->createQuery('a')->where('id_poste=5')
                        ->orderBy('id asc')->execute();
        //  die($marche->getId().'fr');
        $listesdocuments = Doctrine_Core::getTable('lignedocachat')
                        ->createQuery('a')
                        ->where('id_doc=' . $document_achat->getId())
                        ->orderBy('id asc')->execute();
// style="border: 1px solid #000;"
        $html.= $document_achat->ReadHtmlBonCommandeInterneMarche($aviss, $listesdocuments);

        $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
        $query = "SELECT financement.id as idfinancement, financement.mntht as mntht, financement.mntttc,"
                . " financement.mnttva, financement.tauxtva as tva,financement.id_tva as id_tva ,"
                . " financement.caracteristiqueprix as caractere, financement.natureprix as nature,"
                . " titrebudjet.libelle as titre, sourcesbudget.source as budget, "
                . " ligprotitrub.id_titre, ligprotitrub.id_rubrique as id_rubrique, ligprotitrub.id_rubrique as id_sousrubrique,"
                . " titrebudjet.id_projet, titrebudjet.id_source as id_budget, rubrique.libelle as sousrubrique "
                . " FROM financement, ligprotitrub, sourcesbudget, titrebudjet, rubrique "
                . " WHERE financement.id_lignebudget = ligprotitrub.id "
                . " AND ligprotitrub.id_titre = titrebudjet.id "
                . " AND ligprotitrub.id_rubrique = rubrique.id "
                . " AND titrebudjet.id_source = sourcesbudget.id "
                . " AND financement.id_marche=" . $id;
        $finance_listes = $conn->fetchAssoc($query);

        $html.='<h2 style="background-color:#ECECEC;"> Financement</h2>';
        $html.='<h4>Information sur le Financement</h4>';
        $html.='<table class="tableligne" style="width:100%; font-size:12px;">
                    <tr style="background-color:#DEDEDE;">
                        <th style="width:10%;">Budget</th>
                        <th style="width:14%;">Titre</th>
                        <th style="width:10%;">Rubrique</th>
                        <th style="width:13%;">Montant HTVA</th>
                        <th style="width:8%;">Taux TVA</th>
                        <th style="width:13%;">Montant Tva</th>
                        <th style="width:13%;">Montant TTC</th>
                        <th style="width:10%;">Nature des Prix</th>
                        <th style="width:10%;">Caract. prix</th>
                    </tr>';

        for ($i = 0; $i < sizeof($finance_listes); $i++) {
            $html.='<tr>
                        <td>' . $finance_listes[$i]['budget'] . '</td>
                        <td>' . $finance_listes[$i]['titre'] . '</td>
                        <td>' . $finance_listes[$i]['rubrique'] . ' ' . $finance_listes['sousrubrique'] . '</td>
                        <td>' . $finance_listes[$i]['mntht'] . '</td>
                        <td>' . $finance_listes[$i]['tva'] . '</td>
                        <td>' . $finance_listes[$i]['mnttva'] . '</td>
                        <td>' . $finance_listes[$i]['mntttc'] . '</td>
                        <td>' . $finance_listes[$i]['nature'] . '</td>
                        <td>' . $finance_listes[$i]['caractere'] . '</td>
                   </tr>';
        }

        $html.='</table>';

        $html.='<h2 style="background-color:#ECECEC;"> Détails des Décomptes Marché</h2>';
        foreach ($lots as $lot) {
            $detais = Doctrine_Core::getTable('detailprix')->findOneByIdLotsAndIdTypedetailprix($lot->getId(), 3);

            $listesDecompltes = Doctrine_Core::getTable('detailprix')->findByIdLotsAndIdTypedetailprix($lot->getId(), 1);
            if ($listesDecompltes->count() == 0)
                $listesDecompltes = Doctrine_Core::getTable('detailprix')->findByIdLotsAndIdTypedetailprix($lot->getId(), 2);
// style="page-break-inside: avoid;"
            $html.='<h4>Fiche Bénéficiaire</h4>
                <h5>Information Bénéficiaire ' . $lot->getNordre() . ' : ' . $lot->getFournisseur() . '</h5>
                <table class="tableligne" style="width:100%; font-size:12px;">
                    <tbody>
                        <tr style="page-break-inside: avoid;">
                            <td style="width: 20%; text-align:left; background-color:#DEDEDE;"><b>N°Ordre</b></td>
                            <td style="width: 16%">' . $lot->getNordre() . '</td>
                            <td style="width: 13%; text-align:left; background-color:#DEDEDE;"><b>Marchés</b></td>
                            <td style="width: 16%">' . $lot->getMarches() . '</td>
                            <td style="width: 10%; text-align:left; background-color:#DEDEDE;"><b>Fournisseur</b></td>
                            <td style="width: 25%">' . $lot->getFournisseur() . '</td>
                        </tr>
                        <tr >
                            <td style="text-align:left; background-color:#DEDEDE;"><b>TOTAL GENERAL HTVA</b></td>
                            <td>' . $lot->getTotalht() . '</td>
                            <td style="text-align:left; background-color:#DEDEDE;"><b>TVA</b></td>
                            <td>' . $lot->getTva() . '</td>
                            <td style="text-align:left; background-color:#DEDEDE;"><b>RABAIS</b></td>
                            <td>' . $lot->getRrr() . '</td>
                        </tr>
                        <tr>
                            <td style="text-align:left; background-color:#DEDEDE;"><b>T. G. HTVA APRES RABAIS</b></td>
                            <td>' . $lot->getTotalapresrrr() . '</td>
                            <td style="text-align:left; background-color:#DEDEDE;"><b>Net à payer TTC</b></td>
                            <td>' . $lot->getTtcnet() . '</td>
                            <td colspan="2"></td>
                        </tr>
                        <tr>
                            <td style="text-align:left; height: 50px; background-color:#DEDEDE;"><b>Objet</b></td>
                            <td style="text-align:justify;" colspan="5">' . $lot->getObjet() . '</td>
                        </tr>
                    </tbody>
                </table>&nbsp;<br>';

            if ($listesDecompltes->count() > 0) {
                $detail_prix = $listesDecompltes->getFirst();

                $totalht = 0;
                $totalapresrrr = 0;
                $rrr = $lot->getRrr();
                $tauxtva = $lot->getTva()->getValeurtva();
                $ttcnet = 0;

                $liste_sous_detail_prix = Doctrine_Core::getTable('sousdetailprix')
                                ->createQuery('a')->where('id_detail=' . $detail_prix->getId())
                                ->orderBy('id asc')->execute();
                foreach ($liste_sous_detail_prix as $sous_detail_prix) {
                    $totalht = $totalht + $sous_detail_prix->getPrixthtva();
                }

                $totalapresrrr = $totalht * (1 - ($rrr / 100));
                $ttcnet = $totalht * (1 + ($tauxtva / 100));

                $restehtax = $lot->getTotalapresrrr();
                $restettc = $lot->getTtcnet();

                $restettc = $restettc - $ttcnet;
                $restehtax = $restettc / (1 + ($tauxtva / 100));
            }

            $affiche_date_ordre_service = '';
            if ($lot->getDateoservice())
                $affiche_date_ordre_service = date('d/m/Y', strtotime($lot->getDateoservice()));
            $delai_contratctuel = 0;
            if ($marche->getNbrelot() < 2)
                $delai_contratctuel = $marche->getDelai();
            else
                $delai_contratctuel.= $lot->getDelaicontractuelle();

            $stop_date = date('Y-m-d', strtotime($lot->getDelaicontractuelle()));
            //$date_fin = date('Y-m-d', strtotime($lot->getDateoservice()));
            $date_fin = date('Y-m-d', strtotime($lot->getDateoservice() . '+' . $delai_contratctuel . 'day'));
            ///   die($date_fin . 'vf' . $lot->getDelaicontractuelle() . 'de' . $lot->getDateoservice() . 'dcvf' . $delai_contratctuel);
            $date_execution = $date_fin;
            $delai_execution = $delai_contratctuel + $lot->getPeriodejustifier();
            $delai_execution_reele = DifferenceDate::getJours($lot->getDateoservice(), $lot->getDatereceptionprevesoire());
            $diff_retard = $delai_execution_reele - $delai_execution;

            //  if($lot->getMaxpinalite())* floatval($lot->getMaxpinalite()
            $penalte = floatval($diff_retard * $lot->getMarches()->getPenalite());
//            die($delai_execution_reele . 'fd');
            $html.='<div>
            <h5>Délai & Période :</h5>
                <table class="tableligne" style="width:100%;">
                        <tr>
                            <td style="width:15%;text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Date ordre de service :</b></span></td>
                            <td style="width:11%;"><span style="color:#000">' . $affiche_date_ordre_service . ' ' . '</span></td>
                            <td style="width:15%;text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Date réception provisoire :</b></span></td>
                            <td style="width:12%"><span style="color:#000">' . date('d/m/Y', strtotime($lot->getDatereceptionprevesoire())) . ' ' . '</span></td>
                            <td style="width:12%;text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Délai d\'exécution :</b></span></td>
                            <td style="width:12%"><span style="color:#000">' . $delai_execution . ' ' . '</span></td>
                            <td style="width:12%;text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Période d\'arrêt justifié :</b></span></td>
                            <td style="width:11%"><span style="color:#000">' . $lot->getPeriodejustifier() . ' ' . '</span></td>
                        </tr>
                    <tbody>
                        <tr>
                            <td style="text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Délai contractuelle :</b></span></td>
                            <td><span style="color:#000">';
            if ($marche->getNbrelot() < 2)
                $html.= $marche->getDelai();
            else
                $html.= $lot->getDelaicontractuelle();

            $html.= '</span></td>
                            <td style="text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Période réelle d\'exécution :</b></span></td>
                            <td><span style="color:#000">' . $delai_execution_reele . '</span></td>
                            <td style="text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Période de retard :</b></span></td>
                            <td><span style="color:#000">' . $diff_retard . '</span></td>
                            <td style="text-align:left;background-color:#DEDEDE;"><span style="color:#000"><b>Pénalité de retard :</b></span></td>
                            <td>' . $penalte . '</td>
                        </tr>
                    </tbody>
                </table>
                </div>&nbsp;<br>';

            foreach ($listesDecompltes as $detailprix) {
                $html.='<div>
                        <h4><span style="color:#000; font-size:16px;">Sous Détail du Prix :</span></h4>';

                $html.='<table class="tableligne" style="font-size:10px;">
                        <tr>
                            <td style="width:25%; text-align:left;"><span style="color:#000"><b>TOTAL H.TVA :</b> ' . number_format($totalht, 3, ".", ",") . '</span></td>
                            <td style="width:30%; text-align:left;"><span style="color:#000"><b>Rabais, Remises ou Ristourne :</b> ' . $lot->getRrr() . '</span></td>
                            <td style="width:30%; text-align:left;"><span style="color:#000"><b>TOTAL H.TVA APRES RRR :</b> ' . number_format($totalapresrrr, 3, ".", ",") . '</span></td>
                            <td style="width:14%; text-align:left;"><span style="color:#000"><b>T.V.A :</b> ' . $lot->getTva() . '</span></td>
                        </tr>
                        <tr>
                            <td style="text-align:left;"><span style="color:#000"><b>TOTAL T.T.C :</b> ' . number_format($ttcnet, 3, ".", ",") . '</span></td>
                            <td style="text-align:left;"><span style="color:#000"><b>Reste T.T.C :</b> ' . number_format($restettc, 3, ".", ",") . '</span></td>
                            <td style="text-align:left;" colspan="2"><span style="color:#000"><b>Reste H.TAX :</b> ' . number_format($restehtax, 3, ".", ",") . '</span></td>
                        </tr>
                    </table>&nbsp;<br>';

                $html.='<table class="tableligne" style="width:100%;font-size:10px;">
                <tr style="background-color:#DEDEDE;">
                    <th style="width:10%;"></th>
                    <th style="width:10%;">N° du prix</th>
                    <th style="width:30%;">DESIGNATION DES TRAVAUX</th>
                    <th style="width:10%;">UNITE</th>
                    <th style="width:10%;">Qte.</th>
                    <th style="width:15%;">Prix unitaire<br>HTVA</th>
                    <th style="width:15%;">Prix Total<br>HTVA</th>
                </tr>
                <tbody>';

                $liste_sous_detail_prix = Doctrine_Core::getTable('sousdetailprix')
                                ->createQuery('a')->where('id_detail=' . $detailprix->getId())
                                ->orderBy('id asc')->execute();
                foreach ($liste_sous_detail_prix as $sous_detail_prix) {
                    $html.='<tr>
                        <td style="text-align:center;"><span style="color:#000">' . Ucfirst(trim($sous_detail_prix->getTypeavenant())) . '</span></td>
                        <td style="text-align:center;"><span style="color:#000">' . $sous_detail_prix->getNordre() . '</span></td>
                        <td style="text-align:left;"><span style="color:#000">' . $sous_detail_prix->getDesignation() . '</span></td>
                        <td style="text-align:left;"><span style="color:#000">' . $sous_detail_prix->getUnitemarche() . '</span></td>
                        <td style="text-align:center;"><span style="color:#000">' . $sous_detail_prix->getQuetiteant() . '</span></td>
                        <td><span style="color:#000">' . $sous_detail_prix->getPrixunitaire() . '</span></td>';

                    if ($sous_detail_prix->getQuetiteant() > 0):
                        $html.='<td style="text-align:center;"><span style="color:#000">' . number_format($sous_detail_prix->getQuetiteant() * $sous_detail_prix->getPrixunitaire(), 3, ".", ",") . '</span></td>';
                    else:
                        $html.='<td style="text-align:center;"></td>';
                    endif;

                    $html.='</tr>';
                }

                $html.='</tbody>
                </table>
                </div>';
            }
        }

        return $html;
    }

}
