<?php

/**
 * MarqueimmobilisationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarqueimmobilisationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarqueimmobilisationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Marqueimmobilisation');
    }
}