<?php

/**
 * MethodeConclusionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MethodeConclusionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MethodeConclusionTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MethodeConclusion');
    }
}