<?php

/**
 * MotifabsenceinactiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MotifabsenceinactiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MotifabsenceinactiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Motifabsenceinactive');
    }
}