<?php

/**
 * Mouvementbanciare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mouvementbanciare extends BaseMouvementbanciare {

    public function ReadHtmlMouvementsBanque($ids) {

        $mouvements = MouvementbanciareTable::getInstance()->getByListeId($ids);
        $details_banque_ccp = $mouvements->getFirst();

        $html = '';

        $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td>';
        if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
            $html.='<b>Compte CCP</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle();
        else:
            $html.='<b>Compte Bancaire</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle();
        endif;

        $html.='</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>';
        if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
            $html.='<td><b>RIB CCP</b><br>' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>';
        else:
            $html.='<td><b>RIB Banque</b><br>' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>';
        endif;
        $html.='</tr>
                            </table>
                        </td>
                    </tr>
                </table>';

        $html.='<br><div style="width:100%;text-align:center;"><b>' . date('d/m/Y') . '</b></div><br>';

        $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;">
                    <thead>
                        <tr>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>التاريخ<br>DATE</b></th>
                            <th style="width:34%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>العملية<br>OPERATION</b></th>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>تاريخ القيمة<br>VALEUR</b></th>
                            <th style="width:19%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>عليه<br>DEBIT</b></th>
                            <th style="width:19%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>له<br>CREDIT</b></th>
                        </tr>
                    </thead>
                    <tbody>';

        $sDateFin = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m", strtotime($details_banque_ccp->getDateoperation())), 0, date("Y", strtotime($details_banque_ccp->getDateoperation()))));

        $html.='<tr>
                        <td style="width:14%;text-align:center;height:40px;border-left-width:1px;border-right-width:1px;"></td>
                        <td style="width:34%;text-align:left;border-right-width:1px;">SOLDE AU</td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($sDateFin)) . '</td>';
        if ($details_banque_ccp->getDebit() != null):
            $html.='<td style="width:19%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() + $details_banque_ccp->getDebit(), 3, '.', ' ') . '</td>';
        else:
            $html.='<td style="width:19%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() - $details_banque_ccp->getCredit(), 3, '.', ' ') . '</td>';
        endif;
        $html.='</tr>';


        foreach ($mouvements as $mvt):
            $html.='<tr>
                        <td style="width:14%;text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:34%;text-align:left;border-right-width:1px;"><div style="width:100%;">' . $mvt->getInstrumentpaiment()->getLibelle() . '</div></td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>';
            if ($mvt->getDebit() != null):
                $html.='<td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>
                        <td style="width:19%;text-align:right;border-right-width:1px;"></td>';
            else:
                $html.='<td style="width:19%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($mvt->getCredit(), 3, '.', ' ') . '</td>';
            endif;
            $html.='</tr>';
            if ($mvt->getMntenoper() != null):
                $html.='<tr>
                        <td style="width:14%;text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:34%;text-align:left;border-right-width:1px;">' . $mvt->getTypeoperation()->getLibelle() . ' (Commission)</td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($mvt->getMntenoper(), 3, '.', ' ') . '</td>
                        <td style="width:19%;text-align:right;border-right-width:1px;"></td>
                    </tr>';
            endif;
        endforeach;
        $html.='<tr>
                        <td style="width:14%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="text-align:right;border-right-width:1px;border-top-width:1px;"><b>الرصيد الجديد<br>Solde à Nouveau</b></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;border-left-width:1px;border-bottom-width:1px;border-top-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">' . number_format($mvt->getSolde() - $mvt->getMntenoper(), 3, '.', ' ') . '</td>
                    </tr>';

        $html.='</tbody>
                </table>';

        return $html;
    }

    public function ReadHtmlSearchMouvementsBanque($date_debut, $date_fin, $id_banque) {

        $mouvements = MouvementbanciareTable::getInstance()->findAllMouvement($date_debut, $date_fin, $id_banque);

        if ($date_debut != '')
            $date_debut = date('d/m/Y', strtotime($date_debut));
        else
            $date_debut = '--/--/----';
        if ($date_fin != '')
            $date_fin = date('d/m/Y', strtotime($date_fin));
        else
            $date_fin = '--/--/----';

        $details_banque_ccp = $mouvements->getFirst();

        $html = '';

        if ($mouvements->count() >= 1) {

            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td>';
            if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
                $html.='<b>Compte CCP</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle();
            else:
                $html.='<b>Compte Bancaire</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle();
            endif;

            $html.='</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Relevé des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>';
            if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
                $html.='<td><b>RIB CCP</b><br>' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>';
            else:
                $html.='<td><b>RIB Banque</b><br>' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>';
            endif;
            $html.='</tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            $html.='<br><div style="width:100%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</div><br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;">
                    <thead>
                        <tr>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>التاريخ<br>DATE</b></th>
                            <th style="width:34%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>العملية<br>OPERATION</b></th>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>تاريخ القيمة<br>VALEUR</b></th>
                            <th style="width:19%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>عليه<br>DEBIT</b></th>
                            <th style="width:19%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>له<br>CREDIT</b></th>
                        </tr>
                    </thead>
                    <tbody>';

            $sDateFin = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m", strtotime($details_banque_ccp->getDateoperation())), 0, date("Y", strtotime($details_banque_ccp->getDateoperation()))));

            $html.='<tr>
                        <td style="width:14%;text-align:center;height:40px;border-left-width:1px;border-right-width:1px;"></td>
                        <td style="width:34%;text-align:left;border-right-width:1px;">SOLDE AU</td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($sDateFin)) . '</td>';
            if ($details_banque_ccp->getDebit() != null):
                $html.='<td style="width:19%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() + $details_banque_ccp->getDebit(), 3, '.', ' ') . '</td>';
            else:
                $html.='<td style="width:19%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() - $details_banque_ccp->getCredit(), 3, '.', ' ') . '</td>';
            endif;
            $html.='</tr>';


            foreach ($mouvements as $mvt):
                $html.='<tr>
                        <td style="width:14%;text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:34%;text-align:left;border-right-width:1px;"><div style="width:100%;">' . $mvt->getInstrumentpaiment()->getLibelle() . '</div></td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>';
                if ($mvt->getDebit() != null):
                    $html.='<td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>
                        <td style="width:19%;text-align:right;border-right-width:1px;"></td>';
                else:
                    $html.='<td style="width:19%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($mvt->getCredit(), 3, '.', ' ') . '</td>';
                endif;
                $html.='</tr>';
                if ($mvt->getMntenoper() != null):
                    $html.='<tr>
                        <td style="width:14%;text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:34%;text-align:left;border-right-width:1px;">' . $mvt->getTypeoperation()->getLibelle() . ' (Commission) </td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:19%;text-align:right;border-right-width:1px;">' . number_format($mvt->getMntenoper(), 3, '.', ' ') . '</td>
                        <td style="width:19%;text-align:right;border-right-width:1px;"></td>
                    </tr>';
                endif;
            endforeach;
            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:14%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="text-align:right;border-right-width:1px;border-top-width:1px;"><b>الرصيد الجديد<br>Solde à Nouveau</b></td>
                        <td style="width:19%;text-align:right;border-right-width:1px;border-left-width:1px;border-bottom-width:1px;border-top-width:1px;"></td>
                        <td style="width:19%;text-align:right;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">' . number_format($mvt->getSolde() - $mvt->getMntenoper(), 3, '.', ' ') . '</td>
                    </tr>';

            $html.='</tfoot>
                </table>';
        }else {
            $compte = CaissesbanquesTable::getInstance()->find($id_banque);
            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td>';
            if ($compte->getIdNature() == 1):
                $html.='<b>Compte CCP</b><br>' . $compte->getLibelle();
            else:
                $html.='<b>Compte Bancaire</b><br>' . $compte->getLibelle();
            endif;

            $html.='</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Relevé des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>';
            if ($compte->getIdNature() == 1):
                $html.='<td><b>RIB CCP</b><br>' . $compte->getRib() . '</td>';
            else:
                $html.='<td><b>RIB Banque</b><br>' . $compte->getRib() . '</td>';
            endif;
            $html.='</tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            $html.='<br><div style="width:100%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</div><br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;">
                    <thead>
                        <tr>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>التاريخ<br>DATE</b></th>
                            <th style="width:34%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>العملية<br>OPERATION</b></th>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>تاريخ القيمة<br>VALEUR</b></th>
                            <th style="width:19%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>عليه<br>DEBIT</b></th>
                            <th style="width:19%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>له<br>CREDIT</b></th>
                        </tr>
                    </thead>
                    <tbody>';

            $html.='<tr>
                        <td style="width:100%;text-align:center;height:100px;font-size:14px;font-weight:bold;border-left-width:1px;border-bottom-width:1px;border-right-width:1px;">&nbsp;<br>&nbsp;<br>Pas de mouvements pour ce compte dans cette période</td>
                    </tr>';

            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:14%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="width:48%;text-align:right;border-right-width:1px;border-top-width:1px;"><b>الرصيد الجديد<br>Solde à Nouveau</b></td>
                        <td style="width:19%;text-align:center;border-right-width:1px;border-left-width:1px;border-bottom-width:1px;border-top-width:1px;"> - </td>
                        <td style="width:19%;text-align:center;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"> - </td>
                    </tr>';

            $html.='</tfoot>
                </table>';
        }
        return $html;
    }

    public function ReadHtmlBordereau($ids) {
        $mouvements = MouvementbanciareTable::getInstance()->getByListeId($ids);
        $details_banque_ccp = $mouvements->getFirst();
        $societe = Doctrine_Core::getTable('societe')->findOneById(1);
        if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
            $html = '&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="width: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 200px; text-align: left;"></td>
                            <td style="width: 550px; text-align: center; height: 35px;">' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>
                            <td style="width: 200px; text-align: right;"></td>
                        </tr>
                        <tr>
                            <td style="width: 200px; text-align: left;"></td>
                            <td style="width: 550px; text-align: center; height: 35px;">' . $societe->getRs() . '</td>
                            <td style="width: 200px; text-align: right;"></td>
                        </tr>
                        <tr>
                            <td style="width: 200px; text-align: left;"></td>
                            <td style="width: 550px; text-align: center;">' . $societe->getAdresse() . '</td>
                            <td style="width: 200px; text-align: right;"></td>
                        </tr>
                    </tbody>
                </table>&nbsp;<br>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="width: 100%;">
                        <tbody>';

            $total = 0;
            $i = 1;
            foreach ($mouvements as $mvt):
                $html.='<tr>
                                        <td style="width: 100px;"></td>
                                        <td style="text-align: right; width: 200px; height:30px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>
                                        <td style="width: 320px;">' . $mvt->getRefbenifi() . '</td>
                                        <td style="text-align: center; width: 250px;">' . $mvt->getRibbeni() . '</td>
                                        <td style="text-align: center; width: 80px;">' . $i . '</td>
                                    </tr>';
                $total = $total + $mvt->getDebit();
                $i++;
            endforeach;

            for ($j = $i; $j <= 13; $j++):
                $html.='<tr>
                                        <td style="width: 100px;"></td>
                                        <td style="text-align: right; width: 200px; height:30px;"></td>
                                        <td style="width: 320px;"></td>
                                        <td style="text-align: center; width: 250px;"></td>
                                        <td style="text-align: center; width: 80px;"></td>
                                    </tr>';
            endfor;

            $html.='<tr>
                                    <td></td>
                                    <td style="text-align: right;">' . number_format($total, 3, '.', ' ') . '</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>';

            $html.='</tbody>
                </table>';
        else:
            $html = '';

            $html.='<table cellspacing="0" cellpadding="2" style="width: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 100px; text-align: left;"></td>
                            <td style="width: 350px; text-align: center; height: 35px;">' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>
                            <td style="width: 100px; text-align: right;"></td>
                        </tr>
                        <tr>
                            <td style="width: 100px; text-align: left;"></td>
                            <td style="width: 350px; text-align: center; height: 35px;">' . $societe->getRs() . '</td>
                            <td style="width: 100px; text-align: right;"></td>
                        </tr>
                    </tbody>
                </table>&nbsp;<br>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="width: 100%;">
                        <tbody>';

            $total = 0;
            $i = 1;
            foreach ($mouvements as $mvt):
                $html.='<tr>
                                        <td style="width: 200px;">' . $mvt->getRefbenifi() . '</td>
                                        <td style="text-align: center; width: 300px;">' . $mvt->getRibbeni() . '</td>
                                        <td style="text-align: right; width: 180px; height:30px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>
                                    </tr>';
                $total = $total + $mvt->getDebit();
                $i++;
            endforeach;

            for ($j = $i; $j <= 4; $j++):
                $html.='<tr>
                                        <td style="text-align: right; width: 200px; height:30px;"></td>
                                        <td style="width: 300px;"></td>
                                        <td style="text-align: center; width: 180px;"></td>
                                    </tr>';
            endfor;

            $html.='<tr>
                                    <td></td>
                                    <td></td>
                                    <td style="text-align: right;">' . number_format($total, 3, '.', ' ') . '</td>
                                </tr>';

            $html.='</tbody>
                </table>&nbsp;<br>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="width: 100%;">
                        <tbody>
                            <tr>
                                <td style="width: 180px;"></td>
                                <td style="text-align: center; width: 300px; height: 40px;"><div style="width: 290px;">' . chiffreToLettre::cvnbst($total) . '</div></td>
                                <td style="text-align: center; width: 200px;"></td>
                            </tr>
                            <tr>
                                <td style="width: 180px;"></td>
                                <td style="text-align: center; width: 300px;"><div style="width: 290px;"></div></td>
                                <td style="text-align: center; width: 200px;">' . date('d-m-Y') . '</td>
                            </tr>
                        </tbody>
                </table>';

        endif;

        return $html;
    }

    public function ReadHtmlJournalMouvementsBanque($date_debut, $date_fin, $id_banque, $type) {

        $mouvements = MouvementbanciareTable::getInstance()->findAllMouvement($date_debut, $date_fin, $id_banque);

        if ($date_debut != '')
            $date_debut = date('d/m/Y', strtotime($date_debut));
        else
            $date_debut = '--/--/----';
        if ($date_fin != '')
            $date_fin = date('d/m/Y', strtotime($date_fin));
        else
            $date_fin = '--/--/----';

        $details_banque_ccp = $mouvements->getFirst();

        $html = '';

        if ($mouvements->count() >= 1) {

            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td>';
            if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
                $html.='<b>Compte CCP</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle();
            else:
                $html.='<b>Compte Bancaire</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle();
            endif;

            $html.='</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Journal des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>';
            if ($details_banque_ccp->getCaissesbanques()->getIdNature() == 1):
                $html.='<td><b>RIB CCP</b><br>' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>';
            else:
                $html.='<td><b>RIB Banque</b><br>' . $details_banque_ccp->getCaissesbanques()->getRib() . '</td>';
            endif;
            $html.='</tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            switch ($type) {
                case 'tout':
                    $type = 'Tout';
                    break;
                case 'credit':
                    $type = 'Recettes';
                    break;
                case 'debit':
                    $type = 'Dépenses';
                    break;
                default :
                    $type = 'Tout';
                    break;
            }

            $html.='&nbsp;<br><table style="width:100%;text-align:center;">
                            <tr>';
//                                <td style="width:25%;text-align:left;">
//                                    <b>Fournisseur : </b> ...................<br>
//                                    <b>B. Commande : </b> ...................<br>
//                                    <b>Facture : </b> ...................
//                                </td>';
            $html.='    <td style="width:50%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</td>
                                <td style="width:25%;text-align:right;"><b>Type :</b> ' . $type . '</td>
                            </tr>
                    </table>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;font-size:10px;">
                    <thead>
                        <tr>
                            <th style="width:4%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>N°</b></th>
                            <th style="width:8%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Date paiement</b></th>
                            <th style="width:8%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Bon de Commande</b></th>
                            <th style="width:10%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Ordonnance<br>de paiement</b></th>
                            <th style="width:22%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Libellé</b></th>
                            <th style="width:12%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Bénéficiaire</b></th>
                            <th style="width:7%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Type Op.<br>Référence</b></th>
                            <th style="width:9%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Recette</b></th>
                            <th style="width:9%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Dépenses</b></th>
                            <th style="width:11%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Solde</b></th>
                        </tr>
                    </thead>
                    <tbody>';

//            $sDateFin = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m", strtotime($details_banque_ccp->getDateoperation())), 0, date("Y", strtotime($details_banque_ccp->getDateoperation()))));
            $sDateFin = date('Y-m-d', strtotime($details_banque_ccp->getDateoperation() . ' - 1 days'));

            $html.='<tr class="odd">
                        <td style="width:4%;text-align:center;height:40px;border-left-width:1px;border-right-width:1px;"></td>
                        <td style="width:8%;text-align:center;height:40px;border-right-width:1px;">' . date('d/m/Y', strtotime($sDateFin)) . '</td>
                        <td style="width:8%;text-align:center;height:40px;border-right-width:1px;"></td>
                        <td style="width:10%;text-align:center;height:40px;border-right-width:1px;">';

            $html.='</td>
                        <td style="width:22%;text-align:left;border-right-width:1px;">SOLDE AU ' . date('d/m/Y', strtotime($sDateFin)) . '</td>
                        <td style="width:12%;text-align:center;border-right-width:1px;"></td>
                        <td style="width:7%;text-align:center;border-right-width:1px;"></td>
                        <td style="width:9%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:9%;text-align:right;border-right-width:1px;"></td>';
            if ($details_banque_ccp->getCredit() != null):
                $html.='<td style="width:11%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() + $details_banque_ccp->getCredit(), 3, '.', ' ') . '</td>';
            else:
                $html.='<td style="width:11%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() - $details_banque_ccp->getDebit(), 3, '.', ' ') . '</td>';
            endif;
            $html.='</tr>';
            $odd = '';
            foreach ($mouvements as $mvt):

                $html.='<tr class="' . $odd . '">
                        <td style="width:4%;text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . $mvt->getNumero() . '</td>
                        <td style="width:8%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:8%;text-align:center;border-right-width:1px;">';
                if ($mvt->getDocumentbudget()->getPiecejointbudget()->getFirst() != null)
                    $html.= $mvt->getDocumentbudget()->getPiecejointbudget()->getFirst()->getDocumentachat();
                else
                    $html.= '';
                $html.= '</td>
                        <td style="width:10%;text-align:center;border-right-width:1px;">' . $mvt->getReford() . '</td>
                        <td style="width:22%;text-align:left;border-right-width:1px;"><div style="width:100%;">' . $mvt->getInstrumentpaiment()->getLibelle() . '</div></td>
                        <td style="width:12%;text-align:center;border-right-width:1px;">';
                if ($mvt->getRefbenifi())
                    $html.= $mvt->getRefbenifi();
                $html.=' </td>
                        <td style="width:7%;text-align:center;border-right-width:1px;">' . $mvt->getTypeoperation()->getCodeop() . '</td>';

                if ($mvt->getCredit() != null):
                    $html.='<td style="width:9%;text-align:right;border-right-width:1px;">' . number_format($mvt->getCredit(), 3, '.', ' ') . '</td>
                        <td style="width:9%;text-align:right;border-right-width:1px;"></td>';
                else:
                    $html.='<td style="width:9%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:9%;text-align:right;border-right-width:1px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>';
                endif;
                $html.='<td style="width:11%;text-align:right;border-right-width:1px;">' . number_format($mvt->getSolde(), 3, '.', ' ') . '</td>';
                $html.='</tr>';
                if ($odd == 'odd')
                    $odd = '';
                else
                    $odd = 'odd';
            endforeach;
            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:4%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td style="width:10%;text-align:center;border-top-width:1px;"></td>
                        <td style="width:75%;text-align:right;border-right-width:1px;border-top-width:1px;"><b>Solde Le :<br>' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</b></td>
                        <td style="width:11%;text-align:right;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">' . number_format($mvt->getSolde() - $mvt->getMntenoper(), 3, '.', ' ') . '</td>
                    </tr>';

            $html.='</tfoot>
                </table>';

            $html.='<style>
                        .odd{background-color: #f5f5f5;}
                    </style>';
        }else {
            $compte = CaissesbanquesTable::getInstance()->find($id_banque);
            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td>';
            if ($compte->getIdNature() == 1):
                $html.='<b>Compte CCP</b><br>' . $compte->getLibelle();
            else:
                $html.='<b>Compte Bancaire</b><br>' . $compte->getLibelle();
            endif;

            $html.='</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Journal des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>';
            if ($compte->getIdNature() == 1):
                $html.='<td><b>RIB CCP</b><br>' . $compte->getRib() . '</td>';
            else:
                $html.='<td><b>RIB Banque</b><br>' . $compte->getRib() . '</td>';
            endif;
            $html.='</tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            switch ($type) {
                case 'Tout':
                    $type = 'Tout';
                    break;
                case 'credit':
                    $type = 'Recettes';
                    break;
                case 'debit':
                    $type = 'Dépenses';
                    break;
                default :
                    $type = 'Tout';
                    break;
            }
            $html.='&nbsp;<br><table style="width:100%;text-align:center;">
                            <tr>
                                <td style="width:25%;text-align:left;">
                                    <b>Fournisseur : </b> ...................<br>
                                    <b>B. Commande : </b> ...................<br>
                                    <b>Facture : </b> ...................
                                </td>
                                <td style="width:50%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</td>
                                <td style="width:25%;text-align:right;"><b>Type :</b> ' . $type . '</td>
                            </tr>
                    </table>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;font-size:10px;">
                    <thead>
                        <tr>
                            <th style="width:4%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>N°</b></th>
                            <th style="width:8%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Date paiement</b></th>
                            <th style="width:8%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Bon de Commande</b></th>
                            <th style="width:10%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Ordonnance<br>de paiement</b></th>
                            <th style="width:22%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Libellé</b></th>
                            <th style="width:12%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Bénéficiaire</b></th>
                            <th style="width:7%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Type Op.<br>Référence</b></th>
                            <th style="width:9%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Recette</b></th>
                            <th style="width:9%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Dépenses</b></th>
                            <th style="width:11%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Solde</b></th>
                        </tr>
                    </thead>
                    <tbody>';

            $html.='<tr>
                        <td style="width:100%;text-align:center;height:100px;font-size:14px;font-weight:bold;border-left-width:1px;border-bottom-width:1px;border-right-width:1px;">&nbsp;<br>&nbsp;<br>Pas de mouvements pour ce compte dans cette période</td>
                    </tr>';

            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:14%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="width:74%;text-align:right;border-right-width:1px;border-top-width:1px;"><b>Solde</b></td>
                        <td style="width:12%;text-align:center;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"> - </td>
                    </tr>';

            $html.='</tfoot>
                </table>';
        }
        return $html;
    }

    public function ReadHtmlMouvementsCaisse($ids) {

        $mouvements = MouvementbanciareTable::getInstance()->getByListeId($ids);
        $details_banque_ccp = $mouvements->getFirst();

        $html = '';

        $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td><b>Caisse</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle() . '</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr><td><b>Date</b><br>' . date('d/m/Y') . '</td></tr>
                            </table>
                        </td>
                    </tr>
                </table>&nbsp;<br>';

        $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;">
                    <thead>
                        <tr>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>التاريخ<br>DATE</b></th>
                            <th style="width:38%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>العملية<br>OPERATION</b></th>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>تاريخ القيمة<br>VALEUR</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>عليه<br>DEBIT</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>له<br>CREDIT</b></th>
                        </tr>
                    </thead>
                    <tbody>';

        $sDateFin = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m", strtotime($details_banque_ccp->getDateoperation())), 0, date("Y", strtotime($details_banque_ccp->getDateoperation()))));

        $html.='<tr>
                        <td style="width:14%;text-align:center;height:40px;border-left-width:1px;border-right-width:1px;"></td>
                        <td style="width:38%;text-align:left;border-right-width:1px;">SOLDE AU</td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($sDateFin)) . '</td>';
        if ($details_banque_ccp->getDebit() != null):
            $html.='<td style="width:17%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:17%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() + $details_banque_ccp->getDebit(), 3, '.', ' ') . '</td>';
        else:
            $html.='<td style="width:17%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:17%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() - $details_banque_ccp->getCredit(), 3, '.', ' ') . '</td>';
        endif;
        $html.='</tr>';


        foreach ($mouvements as $mvt):
            $html.='<tr>
                        <td style="text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="text-align:left;border-right-width:1px;"><div style="width:100%;">' . $mvt->getNomoperation() . '</div></td>
                        <td style="text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>';
            if ($mvt->getDebit() != null):
                $html.='<td style="text-align:right;border-right-width:1px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>
                        <td style="text-align:right;border-right-width:1px;"></td>';
            else:
                $html.='<td style="text-align:right;border-right-width:1px;"></td>
                        <td style="text-align:right;border-right-width:1px;">' . number_format($mvt->getCredit(), 3, '.', ' ') . '</td>';
            endif;
            $html.='</tr>';
        endforeach;
        $html.='<tr>
                        <td style="text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="text-align:right;border-right-width:1px;border-top-width:1px;"><b>الرصيد الجديد<br>Solde à Nouveau</b></td>
                        <td style="text-align:right;border-right-width:1px;border-left-width:1px;border-bottom-width:1px;border-top-width:1px;"></td>
                        <td style="text-align:right;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">' . number_format($mvt->getSolde(), 3, '.', ' ') . '</td>
                    </tr>';

        $html.='</tbody>
                </table>';

        return $html;
    }

    public function ReadHtmlSearchMouvementsCaisse($date_debut, $date_fin, $id_banque) {

        $mouvements = MouvementbanciareTable::getInstance()->findAllMouvement($date_debut, $date_fin, $id_banque);

        if ($date_debut != '')
            $date_debut = date('d/m/Y', strtotime($date_debut));
        else
            $date_debut = '--/--/----';
        if ($date_fin != '')
            $date_fin = date('d/m/Y', strtotime($date_fin));
        else
            $date_fin = '--/--/----';

        $details_banque_ccp = $mouvements->getFirst();

        $html = '';

        if ($mouvements->count() >= 1) {

            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td><b>Caisse</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle() . '</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Relevé des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr><td><b>Date</b><br>' . date('H:i d/m/Y') . '</td></tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            $html.='<br><div style="width:100%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</div><br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;">
                    <thead>
                        <tr>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>التاريخ<br>DATE</b></th>
                            <th style="width:38%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>العملية<br>OPERATION</b></th>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>تاريخ القيمة<br>VALEUR</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>عليه<br>DEBIT</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>له<br>CREDIT</b></th>
                        </tr>
                    </thead>
                    <tbody>';

            $sDateFin = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m", strtotime($details_banque_ccp->getDateoperation())), 0, date("Y", strtotime($details_banque_ccp->getDateoperation()))));

            $html.='<tr>
                        <td style="width:14%;text-align:center;height:40px;border-left-width:1px;border-right-width:1px;"></td>
                        <td style="width:38%;text-align:left;border-right-width:1px;">SOLDE AU</td>
                        <td style="width:14%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($sDateFin)) . '</td>';
            if ($details_banque_ccp->getDebit() != null):
                $html.='<td style="width:17%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:17%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() + $details_banque_ccp->getDebit(), 3, '.', ' ') . '</td>';
            else:
                $html.='<td style="width:17%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:17%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() - $details_banque_ccp->getCredit(), 3, '.', ' ') . '</td>';
            endif;
            $html.='</tr>';


            foreach ($mouvements as $mvt):
                $html.='<tr>
                        <td style="text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="text-align:left;border-right-width:1px;"><div style="width:100%;">' . $mvt->getNomoperation() . '</div></td>
                        <td style="text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>';
                if ($mvt->getDebit() != null):
                    $html.='<td style="text-align:right;border-right-width:1px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>
                        <td style="text-align:right;border-right-width:1px;"></td>';
                else:
                    $html.='<td style="text-align:right;border-right-width:1px;"></td>
                        <td style="text-align:right;border-right-width:1px;">' . number_format($mvt->getCredit(), 3, '.', ' ') . '</td>';
                endif;
                $html.='</tr>';
            endforeach;
            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="text-align:right;border-right-width:1px;border-top-width:1px;"><b>الرصيد الجديد<br>Solde à Nouveau</b></td>
                        <td style="text-align:right;border-right-width:1px;border-left-width:1px;border-bottom-width:1px;border-top-width:1px;"></td>
                        <td style="text-align:right;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">' . number_format($mvt->getSolde() - $mvt->getMntenoper(), 3, '.', ' ') . '</td>
                    </tr>';

            $html.='</tfoot>
                </table>';
        }else {
            $compte = CaissesbanquesTable::getInstance()->find($id_banque);
            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td><b>Caisse</b><br>' . $compte->getLibelle() . '</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Relevé des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr><td><b>Date</b><br>' . date('H:i d/m/Y') . '</td></tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            $html.='<br><div style="width:100%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</div><br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;">
                    <thead>
                        <tr>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>التاريخ<br>DATE</b></th>
                            <th style="width:38%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>العملية<br>OPERATION</b></th>
                            <th style="width:14%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>تاريخ القيمة<br>VALEUR</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>عليه<br>DEBIT</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>له<br>CREDIT</b></th>
                        </tr>
                    </thead>
                    <tbody>';

            $html.='<tr>
                        <td style="width:100%;text-align:center;height:100px;font-size:14px;font-weight:bold;border-left-width:1px;border-bottom-width:1px;border-right-width:1px;">&nbsp;<br>&nbsp;<br>Pas de mouvements pour cette caisse dans cette période</td>
                    </tr>';

            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:14%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="width:48%;text-align:right;border-right-width:1px;border-top-width:1px;"><b>الرصيد الجديد<br>Solde à Nouveau</b></td>
                        <td style="width:17%;text-align:center;border-right-width:1px;border-left-width:1px;border-bottom-width:1px;border-top-width:1px;"> - </td>
                        <td style="width:17%;text-align:center;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"> - </td>
                    </tr>';

            $html.='</tfoot>
                </table>';
        }
        return $html;
    }

    public function ReadHtmlJournalMouvementsCaisse($date_debut, $date_fin, $id_banque, $type) {

        $mouvements = MouvementbanciareTable::getInstance()->findAllMouvement($date_debut, $date_fin, $id_banque);

        if ($date_debut != '')
            $date_debut = date('d/m/Y', strtotime($date_debut));
        else
            $date_debut = '--/--/----';
        if ($date_fin != '')
            $date_fin = date('d/m/Y', strtotime($date_fin));
        else
            $date_fin = '--/--/----';

        $html = '';

        if ($mouvements->count() >= 1) {
            $details_banque_ccp = $mouvements->getFirst();

            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td><b>Caisse</b><br>' . $details_banque_ccp->getCaissesbanques()->getLibelle() . '</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Journal des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr><td><b>Date</b><br>' . date('H:i d/m/Y') . '</td></tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            switch ($type) {
                case 'tout':
                    $type = 'Tout';
                    break;
                case 'credit':
                    $type = 'Recettes';
                    break;
                case 'debit':
                    $type = 'Dépenses';
                    break;
                default :
                    $type = 'Tout';
                    break;
            }

            $html.='&nbsp;<br><table style="width:100%;text-align:center;">
                            <tr>
                                <td style="width:25%;text-align:left;">
                                    <b>Fournisseur : </b> ...................
                                </td>
                                <td style="width:50%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</td>
                                <td style="width:25%;text-align:right;"><b>Type :</b> ' . $type . '</td>
                            </tr>
                    </table>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;font-size:10px;">
                    <thead>
                        <tr>
                            <th style="width:5%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>N°</b></th>
                            <th style="width:8%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Date paiement</b></th>
                            <th style="width:12%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>B. de dépenses<br>au comptant</b></th>
                            <th style="width:27%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Libellé</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Bénéficiaire</b></th>
                            <th style="width:10%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Recette</b></th>
                            <th style="width:10%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Dépenses</b></th>
                            <th style="width:11%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Solde</b></th>
                        </tr>
                    </thead>
                    <tbody>';

//            $sDateFin = date("Y-m-d H:i:s", mktime(0, 0, 0, date("m", strtotime($details_banque_ccp->getDateoperation())), 0, date("Y", strtotime($details_banque_ccp->getDateoperation()))));
            $sDateFin = date('Y-m-d', strtotime($details_banque_ccp->getDateoperation() . ' - 1 days'));

            $html.='<tr class="odd">
                        <td style="width:5%;text-align:center;height:40px;border-left-width:1px;border-right-width:1px;"></td>
                        <td style="width:8%;text-align:center;height:40px;border-right-width:1px;">' . date('d/m/Y', strtotime($sDateFin)) . '</td>
                        <td style="width:12%;text-align:center;height:40px;border-right-width:1px;"></td>
                        <td style="width:27%;text-align:left;border-right-width:1px;">SOLDE AU ' . date('d/m/Y', strtotime($sDateFin)) . '</td>
                        <td style="width:17%;text-align:center;border-right-width:1px;"></td>
                        <td style="width:10%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:10%;text-align:right;border-right-width:1px;"></td>';
            if ($details_banque_ccp->getCredit() != null):
                $html.='<td style="width:11%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() + $details_banque_ccp->getCredit(), 3, '.', ' ') . '</td>';
            else:
                $html.='<td style="width:11%;text-align:right;border-right-width:1px;">' . number_format($details_banque_ccp->getSolde() - $details_banque_ccp->getDebit(), 3, '.', ' ') . '</td>';
            endif;
            $html.='</tr>';
            $odd = '';
            foreach ($mouvements as $mvt):

                $html.='<tr class="' . $odd . '">
                        <td style="width:5%;text-align:center;height:25px;border-left-width:1px;border-right-width:1px;">' . $mvt->getNumero() . '</td>
                        <td style="width:8%;text-align:center;border-right-width:1px;">' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</td>
                        <td style="width:12%;text-align:center;border-right-width:1px;">' . $mvt->getReford() . '</td>
                        <td style="width:27%;text-align:left;border-right-width:1px;"><div style="width:100%;">' . $mvt->getNomoperation() . '</div></td>
                        <td style="width:17%;text-align:center;border-right-width:1px;">' . $mvt->getRefbenifi() . '</td>';

                if ($mvt->getCredit() != null):
                    $html.='<td style="width:10%;text-align:right;border-right-width:1px;">' . number_format($mvt->getCredit(), 3, '.', ' ') . '</td>
                        <td style="width:10%;text-align:right;border-right-width:1px;"></td>';
                else:
                    $html.='<td style="width:10%;text-align:right;border-right-width:1px;"></td>
                        <td style="width:10%;text-align:right;border-right-width:1px;">' . number_format($mvt->getDebit(), 3, '.', ' ') . '</td>';
                endif;
                $html.='<td style="width:11%;text-align:right;border-right-width:1px;">' . number_format($mvt->getSolde(), 3, '.', ' ') . '</td>';
                $html.='</tr>';
                if ($odd == 'odd')
                    $odd = '';
                else
                    $odd = 'odd';
            endforeach;
            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:4%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td style="width:10%;text-align:center;border-top-width:1px;"></td>
                        <td style="width:75%;text-align:right;border-right-width:1px;border-top-width:1px;"><b>Solde Le :<br>' . date('d/m/Y', strtotime($mvt->getDateoperation())) . '</b></td>
                        <td style="width:11%;text-align:right;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">' . number_format($mvt->getSolde() - $mvt->getMntenoper(), 3, '.', ' ') . '</td>
                    </tr>';

            $html.='</tfoot>
                </table>';

            $html.='<style>
                        .odd{background-color: #f5f5f5;}
                    </style>';
        }else {
            $compte = CaissesbanquesTable::getInstance()->find($id_banque);
            $html.='<table>
                    <tr>
                        <td style="40%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr>
                                    <td><b>Caisse</b><br>' . $compte->getLibelle() . '</td>
                                </tr>
                            </table>
                        </td>
                        <td style="30%;"><h3>&nbsp;<br><u>Journal des Mouvements</u></h3></td>
                        <td style="30%;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;">
                            <table style="padding:2%;">
                                <tr><td><b>Date</b><br>' . date('H:i d/m/Y') . '</td></tr>
                            </table>
                        </td>
                    </tr>
                </table>';

            switch ($type) {
                case 'Tout':
                    $type = 'Tout';
                    break;
                case 'credit':
                    $type = 'Recettes';
                    break;
                case 'debit':
                    $type = 'Dépenses';
                    break;
                default :
                    $type = 'Tout';
                    break;
            }
            $html.='&nbsp;<br><table style="width:100%;text-align:center;">
                            <tr>
                                <td style="width:25%;text-align:left;">
                                    <b>Fournisseur : </b> ...................
                                </td>
                                <td style="width:50%;text-align:center;"><b>Période De : </b>' . $date_debut . '<b> jusqu\'à </b>' . $date_fin . '</td>
                                <td style="width:25%;text-align:right;"><b>Type :</b> ' . $type . '</td>
                            </tr>
                    </table>&nbsp;<br>';

            $html.='<table cellspacing="0" cellpadding="2" style="margin:0px;font-size:10px;">
                    <thead>
                        <tr>
                            <th style="width:5%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>N°</b></th>
                            <th style="width:8%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Date paiement</b></th>
                            <th style="width:12%;text-align:center;background-color:#EDEDED;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>B. de dépenses<br>au comptant</b></th>
                            <th style="width:27%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Libellé</b></th>
                            <th style="width:17%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Bénéficiaire</b></th>
                            <th style="width:10%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Recette</b></th>
                            <th style="width:10%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Dépenses</b></th>
                            <th style="width:11%;text-align:center;background-color:#EDEDED;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"><b>Solde</b></th>
                        </tr>
                    </thead>
                    <tbody>';

            $html.='<tr>
                        <td style="width:100%;text-align:center;height:100px;font-size:14px;font-weight:bold;border-left-width:1px;border-bottom-width:1px;border-right-width:1px;">&nbsp;<br>&nbsp;<br>Pas de mouvements pour cette caisse dans cette période</td>
                    </tr>';

            $html.='</tbody>
            <tfoot>
            <tr>
                        <td style="width:14%;text-align:center;height:25px;border-top-width:1px;"></td>
                        <td colspan="2" style="width:74%;text-align:right;border-right-width:1px;border-top-width:1px;"><b>Solde</b></td>
                        <td style="width:12%;text-align:center;border-left-width:1px;border-right-width:1px;border-bottom-width:1px;border-top-width:1px;"> - </td>
                    </tr>';

            $html.='</tfoot>
                </table>';
        }
        return $html;
    }

}
