<?php

/**
 * NatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nature');
    }
}