<?php

/**
 * NoteprofessionnelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoteprofessionnelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoteprofessionnelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Noteprofessionnel');
    }
}