<?php

/**
 * PaieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaieTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PaieTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Paie');
    }

    public function loadAllFiltre($id_agents = '', $annee = '') {
        $q = Doctrine_Query::create()
                ->select('p.*')
                ->from('paie p')
                ->where('p.annee = ?', $annee);
        if ($id_agents != '')
            $q = $q->andWhere('p.id_agents =' . $id_agents);

        return $q;
    }

}
