<?php

/**
 * PapierchequeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PapierchequeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object PapierchequeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Papiercheque');
    }

    public function getByListeRefpapier($references) {
        $q = $this->createQuery('pc')
                ->whereIn('pc.refpapier', (array) $references)
                ->execute();
        return $q;
    }

    public function getListeChequeByCarnets($id) {
        $q = $this->createQuery('pc')
                ->select("p.id, p.refpapier")
                ->from('Papiercheque p')
                ->leftJoin('p.Carnetcheque c')
                ->where("c.id_banque=" . $id)
                ->andwhere('p.datesignature is null')
                ->andWhere('p.etat = false')
                ->andWhere('p.annule = false')
                ->execute();
        return $q;
    }

}
