<?php

/**
 * ParametreamortissementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametreamortissementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametreamortissementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parametreamortissement');
    }
}