<?php

/**
 * ParametragesocieteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParametragesocieteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParametragesocieteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parametragesociete');
    }
}