<?php

/**
 * ParentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parents');
    }
}