<?php

/**
 * PositionadministratifTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PositionadministratifTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PositionadministratifTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Positionadministratif');
    }
}