<?php

/**
 * Posterh
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProjectTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Posterh extends BasePosterh {

    public function __toString() {
        return $this->getUnite() . '' . $this->getLibelle();
    }

    public function ReadHtmlAlllistePoste($idd) {

        $html = ' <h3>Liste des Postes </h3>'
        ;
        $html.=
                '<table border="1" style="padding:1%">
           
            <tbody>
                <tr>
                    <td style="width: 20%;"><b><label>Numéro</label></b></td>
                    <td style="width: 80% text-align:left;"><b><label>Libellé</label></b></td>
                 
                 
                </tr>
                ';

        $sousd = Doctrine_Core::getTable('posterh')->findAll();


        $i = 1;
        foreach ($sousd as $p):
            $html.= '<tr>'
                    . '<td>' . $i . '</td>'
                    . '<td style="text-align:left;">' . $p->getLibelle() . '</td>'
                    . '</tr>';
            $i++;
        endforeach;
        $html.='<tbody></table>';

        return $html;
    }

    public function ReadHtmlAlllistepostepardirection($idd) {
  $direction = Doctrine_Core::getTable('direction')->findOneById($idd); 
        $html = ' <h3>Liste des Postes reliés au "'.$direction->getLibelle().'"</h3>'
        ;
        $html.=
                '<table border="1" style="padding:1%">
           
            <tbody>
                <tr>
                    <td style="width: 20%;"><b><label>Numéro</label></b></td>
                    <td style="width: 80% text-align:left;"><b><label>Libellé</label></b></td>
                 
                 
                </tr>
                ';

        $sousd = Doctrine_Core::getTable('posterh')
                ->createQuery('a')
                ->select("*")
                ->from('posterh p ,unite u, servicerh s , sousdirection sd , direction d')
                ->where('p.id_unite=u.id and u.id_service=s.id and s.id_sousdirection=sd.id')
                ->andwhere('sd.id_direction=' . $idd)
                ->execute();


        $i = 1;
        foreach ($sousd as $p):
            $html.= '<tr>'
                    . '<td>' . $i . '</td>'
                    . '<td style="text-align:left;">' . $p->getLibelle() . '</td>'
                    . '</tr>';
            $i++;
        endforeach;
        $html.='<tbody></table>';

        return $html;
    }

//par service

    public function ReadHtmlAlllisteposteparservice($idd) {
$service = Doctrine_Core::getTable('servicerh')->findOneById($idd); 
        $html = ' <h3>Liste des Postes reliés au "'.$service->getLibelle().'"</h3>'
        ;
        $html.=
                '<table border="1" style="padding:1%">
           
            <tbody>
                <tr>
                    <td style="width: 20%;"><b><label>Numéro</label></b></td>
                    <td style="width: 80% text-align:left;"><b><label>Libellé</label></b></td>
                 
                 
                </tr>
                ';

        $sousd = Doctrine_Core::getTable('posterh')
                ->createQuery('a')
                ->select("*")
                ->from('posterh p ,unite u')
                ->where('p.id_unite=u.id ')
                ->andwhere('u.id_service=' . $idd)
                ->execute();


        $i = 1;
        foreach ($sousd as $p):
            $html.= '<tr>'
                    . '<td>' . $i . '</td>'
                    . '<td style="text-align:left;">' . $p->getLibelle() . '</td>'
                    . '</tr>';
            $i++;
        endforeach;
        $html.='<tbody></table>';

        return $html;
    }

    //par sous direction

    public function ReadHtmlAlllisteposteparsousdirection($idd) {
 $directio = Doctrine_Core::getTable('sousdirection')->findOneById($idd); 
        $html = ' <h3>Liste des Postes reliés au "'.$directio->getLibelle().'" </h3>'
        ;
        $html.=
                '<table border="1" style="padding:1%">
           
            <tbody>
                <tr>
                    <td style="width: 20%;"><b><label>Numéro</label></b></td>
                    <td style="width: 80% text-align:left;"><b><label>Libellé</label></b></td>
                 
                 
                </tr>
                ';

        $sousd = Doctrine_Core::getTable('posterh')
                ->createQuery('a')
                ->select("*")
                ->from('posterh p ,unite u, servicerh s , sousdirection sd ')
                ->where('p.id_unite=u.id and u.id_service=s.id')
                ->andwhere('s.id_sousdirection=' . $idd)
                ->execute();


        $i = 1;
        foreach ($sousd as $p):
            $html.= '<tr>'
                    . '<td>' . $i . '</td>'
                    . '<td style="text-align:left;">' . $p->getLibelle() . '</td>'
                    . '</tr>';
            $i++;
        endforeach;
        $html.='<tbody></table>';

        return $html;
    }

//par unite 

    public function ReadHtmlAlllisteposteparunite($idd) {
$unite = Doctrine_Core::getTable('unite')->findOneById($idd); 
        $html = ' <h3>Liste des Postes reliés au "'.$unite->getLibelle().'" </h3>'
        ;
        $html.=
                '<table border="1" style="padding:1%">
           
            <tbody>
                <tr>
                    <td style="width: 20%;"><b><label>Numéro</label></b></td>
                    <td style="width: 80% text-align:left;"><b><label>Libellé</label></b></td>
                 
                 
                </tr>
                ';

        $sousd = Doctrine_Core::getTable('posterh')
                ->createQuery('a')
                ->select("*")
                ->from('posterh p')
                ->where('p.id_unite=' . $idd)
                ->execute();


        $i = 1;
        foreach ($sousd as $p):
            $html.= '<tr>'
                    . '<td>' . $i . '</td>'
                    . '<td style="text-align:left;">' . $p->getLibelle() . '</td>'
                    . '</tr>';
            $i++;
        endforeach;
        $html.='<tbody></table>';

        return $html;
    }

}
