<?php

/**
 * Repartitionsalaireouvrier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Tes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Repartitionsalaireouvrier extends BaseRepartitionsalaireouvrier {

    public function ReadHtmlRepartition(sfWebRequest $request) {
        $id = $request->getParameter('id', '');

        $repartition = RepartitionsalaireouvrierTable::getInstance()->find($id);
        $societe = SocieteTable::getInstance()->findAll()->getFirst();

        $html = '<div border="1">
                    <table cellspacing="0" cellpadding="3">
                        <tr align="center">
                            <td style="font-weight:bold;font-size:18px;width:100%;">' . $societe->getRs() . '</td>
                        </tr>
                        <tr align="center">
                            <td style="font-weight:bold;font-size:14px;width:100%;">Répartition mensuelle par chantier <br> paie des ouvriers ' . $repartition->getAnnee() . '</td>
                        </tr>
                    </table>
                </div>&nbsp;<br>';

        $html.= '<table cellspacing="0">
                <tr>
                    <td style="width:49%;">
                        <table cellspacing="0" cellpadding="5" border="1">
                            <tr>
                                <td style="font-size:12px;width:47%;background-color:#F3F3F3;"><b>Année :</b></td>
                                <td style="font-size:12px;width:53%;"><b>' . $repartition->getAnnee() . '</b></td>
                            </tr>
                            <tr>
                                <td style="font-size:12px;width:47%;background-color:#F3F3F3;"><b>Nombre Total des Jours :</b></td>
                                <td style="font-size:12px;width:53%;"><b>' . $repartition->getJour() . ' jours</b></td>
                            </tr>
                            <tr>
                                <td style="font-size:12px;width:47%;background-color:#F3F3F3;"><b>Montant Total des salaires :</b></td>
                                <td style="font-size:12px;width:53%;"><b>' . number_format($repartition->getMontant(), 3, '.', ' ') . ' TND</b></td>
                            </tr>
                        </table>
                    </td>
                    <td style="width:2%;">&nbsp;</td>
                    <td style="width:49%;">
                        <table cellspacing="0" cellpadding="5" border="1">
                            <thead><tr><th style="font-weight:bold;text-align:center;background-color:#F3F3F3;">Comptes Comptables</th></tr></thead>
                            <tbody>';
        $repartition_comptes = $repartition->getCompterepartitionsalaireouvrier();
        foreach ($repartition_comptes as $repartition_compte):
            $html.= '<tr>
                        <td style = "font-size:12px;width:100%;">' . $repartition_compte->getPlancomptable() . '</td>
                    </tr>';
        endforeach;

        $html.= '</tbody>
                        </table>
                    </td>
                </tr>
                </table>&nbsp;<br>';

        $array_totaux_mois = array();
        for ($i = 1; $i < 13; $i++):
            $array_totaux_mois[$i]['jour'] = 0;
            $array_totaux_mois[$i]['montant'] = 0;
        endfor;

        $html.= '<table cellspacing="0" cellpadding="3" border="1">
                    <tr style="font-weight:bold;text-align:center;background-color:#F3F3F3;">
                        <td colspan="2" style="width:13%;">Chantier (Projet)</td>';
        for ($i = 1; $i < 13; $i++):
            $html.= '<td style="width:6.5%;text-align:center;">' . $i . '</td>';
        endfor;
        $html.= '<td style="width:9%;text-align:center;">Total</td>
                    </tr>';

        $repartition_chantiers = ChantierrepartitionsalaireouvrierTable::getInstance()->getByRepartition($repartition->getId());
        foreach ($repartition_chantiers as $repartition_chantier):

            $lignes = $repartition_chantier->getLignerepartitionsalaireouvrier();
            $array_mois = array();
            for ($i = 1; $i < 13; $i++):
                $array_mois[$i]['jour'] = 0;
                $array_mois[$i]['montant'] = 0;
            endfor;
            foreach ($lignes as $ligne):
                $array_mois[$ligne->getMois()]['jour'] = $ligne->getJour();
                $array_mois[$ligne->getMois()]['montant'] = $ligne->getMontant();

                $array_totaux_mois[$ligne->getMois()]['jour'] = $array_totaux_mois[$ligne->getMois()]['jour'] + $ligne->getJour();
                $array_totaux_mois[$ligne->getMois()]['montant'] = $array_totaux_mois[$ligne->getMois()]['montant'] + $ligne->getMontant();
            endforeach;

            $html.= '<tr style="font-size:9px;">
                            <td rowspan="2" style="width:11%;">' . trim($repartition_chantier->getLibelle()) . '<br>(' . trim($repartition_chantier->getProjet()) . ')</td>
                            <td style="text-align:center;width:2%;">J</td>';
            for ($i = 1; $i < 13; $i++):
                $html.= '<td style="text-align:right;">' . $array_mois[$i]['jour'] . '</td>';
            endfor;
            $html.= '<td style="text-align:center;font-weight:bold;">' . $repartition_chantier->getJour() . '</td>
                </tr>';

            $html.= '<tr style="background-color: #FAFAFA;font-size:9px;">
                    <td style="text-align:center;">M</td>';
            for ($i = 1; $i < 13; $i++):
                $html.= '<td style="text-align:right;">' . number_format($array_mois[$i]['montant'], 3, '.', ' ') . '</td>';
            endfor;
            $html.= '<td style="text-align:right;font-weight:bold;">' . number_format($repartition_chantier->getMontant(), 3, '.', ' ') . '</td>
                </tr>';

        endforeach;

        $html.='<tr style="background-color:#F0F0F0;font-size:9px;">
                    <td style="text-align:center;font-weight:bold;">Nombre de Jours</td>
                    <td style="text-align:center;font-weight:bold;">J</td>';
        for ($i = 1; $i < 13; $i++):
            $html.='<td style="text-align:center;font-weight:bold;">' . $array_totaux_mois[$i]['jour'] . '</td>';
        endfor;
        $html.='<td style="text-align:center;font-weight:bold;">' . $repartition->getJour() . '</td>
                </tr>
                <tr style="background-color: #F0F0F0;font-size:9px;">
                    <td style="text-align:center;font-weight:bold;">Total Brut /mois</td>
                    <td style="text-align:center;font-weight:bold;">M</td>';
        for ($i = 1; $i < 13; $i++):
            $html.='<td style="text-align:right;font-weight:bold;">' . number_format($array_totaux_mois[$i]['montant'], 3, '.', ' ') . '</td>';
        endfor;
        $html.='<td style="text-align:right;font-weight:bold;">' . number_format($repartition->getMontant(), 3, '.', ' ') . '</td>
                </tr>';

        $html.= '</table>';

        return $html;
    }

    public function ReadHtmlRepartitionRecap(sfWebRequest $request) {
        $id = $request->getParameter('id', '');

        $repartition = RepartitionsalaireouvrierTable::getInstance()->find($id);
        $societe = SocieteTable::getInstance()->findAll()->getFirst();

        $html = '<div border="1">
                    <table cellspacing="0" cellpadding="3">
                        <tr align="center">
                            <td style="font-weight:bold;font-size:18px;width:100%;">' . $societe->getRs() . '</td>
                        </tr>
                        <tr align="center">
                            <td style="font-weight:bold;font-size:14px;width:100%;">Récapitulatif par chantier<br>paie des ouvriers ' . $repartition->getAnnee() . '<br><i>~ PAIE DES OUVRIERS AGRICOLE ' . $repartition->getAnnee() . ' ~</i></td>
                        </tr>
                    </table>
                </div>&nbsp;<br>';

        $html.= '<table cellspacing="0">
                <tr>
                    <td style="width:50%;">
                        <table cellspacing="0" cellpadding="5" border="1">
                            <tr>
                                <td style="font-size:10px;width:52%;background-color:#F3F3F3;"><b>Année :</b></td>
                                <td style="font-size:12px;width:48%;"><b>' . $repartition->getAnnee() . '</b></td>
                            </tr>
                            <tr>
                                <td style="font-size:10px;width:52%;background-color:#F3F3F3;"><b>Nombre Total des Jours :</b></td>
                                <td style="font-size:12px;width:48%;"><b>' . $repartition->getJour() . ' jours</b></td>
                            </tr>
                            <tr>
                                <td style="font-size:10px;width:52%;background-color:#F3F3F3;"><b>Montant Total des salaires :</b></td>
                                <td style="font-size:12px;width:48%;"><b>' . number_format($repartition->getMontant(), 3, '.', ' ') . ' TND</b></td>
                            </tr>
                        </table>
                    </td>
                    <td style="width:1%;">&nbsp;</td>
                    <td style="width:49%;">
                        <table cellspacing="0" cellpadding="5" border="1">
                            <thead><tr><th style="font-weight:bold;text-align:center;background-color:#F3F3F3;">Comptes Comptables</th></tr></thead>
                            <tbody>';
        $repartition_comptes = $repartition->getCompterepartitionsalaireouvrier();
        foreach ($repartition_comptes as $repartition_compte):
            $html.= '<tr>
                        <td style = "font-size:12px;width:100%;">' . $repartition_compte->getPlancomptable() . '</td>
                    </tr>';
        endforeach;

        $html.= '</tbody>
                        </table>
                    </td>
                </tr>
                </table>&nbsp;<br>';

        $array_totaux_mois = array();
        for ($i = 1; $i < 13; $i++):
            $array_totaux_mois[$i]['jour'] = 0;
            $array_totaux_mois[$i]['montant'] = 0;
        endfor;

        $html.= '<table cellspacing="0" cellpadding="3" border="1">
                    <tr style="font-weight:bold;background-color:#F3F3F3;">
                        <td style="width:55%;height:30px;">Chantier (Projet)</td>
                        <td style="width:20%;text-align:center;">Nombre Jours</td>
                        <td style="width:25%;text-align:center;">Montant Total</td>
                    </tr>';

        $repartition_chantiers = ChantierrepartitionsalaireouvrierTable::getInstance()->getByRepartition($repartition->getId());
        foreach ($repartition_chantiers as $repartition_chantier):

            $html.= '<tr>
                        <td style="width:55%;height:25px;">' . trim($repartition_chantier->getLibelle()) . ' (' . trim($repartition_chantier->getProjet()) . ')</td>
                        <td style="text-align:center;font-weight:bold;width:20%;">' . $repartition_chantier->getJour() . '</td>
                        <td style="text-align:right;font-weight:bold;width:25%;">' . number_format($repartition_chantier->getMontant(), 3, '.', ' ') . '</td>
                    </tr>';
        endforeach;

        $html.='<tr style="background-color:#F0F0F0;">
                    <td style="text-align:center;font-weight:bold;height:30px;">Total</td>
                    <td style="text-align:center;font-weight:bold;">' . $repartition->getJour() . '</td>
                    <td style="text-align:right;font-weight:bold;">' . number_format($repartition->getMontant(), 3, '.', ' ') . '</td>
                </tr>';

        $html.= '</table>';

        return $html;
    }

}
