<?php

/**
 * RetenuesursalaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RetenuesursalaireTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object RetenuesursalaireTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Retenuesursalaire');
    }

    public function getDemande() {

        $query = $this->createQuery('l');
        $query->select('l.*')
                ->from('Retenuesursalaire l')
                ->where("l.mois <= '" . intval(date("m")) . "'")
                ->orWhere("l.annee <= '" . date("Y") . "'");

        return $query->execute();
    }

}
