<?php

/**
 * Ribbancaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 *  
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ribbancaire extends BaseRibbancaire
{
    public function __toString()
    {
        return ''.$this->getRib();

    }
    public function getEtatRib(){
        if($this->getEtat()==0)
        return 'Actif';
        return 'Bloqué';
    }
}
