<?php

/**
 * RolemoduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolemoduleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolemoduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rolemodule');
    }
}