<?php

/**
 * Situationcumulee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Tes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Situationcumulee extends BaseSituationcumulee {

    public function ReadHtmlRecapSituation(sfWebRequest $request) {
        $min_mois = $request->getParameter('min_mois');
        $max_mois = $request->getParameter('max_mois');
        $titre = $request->getParameter('titre');
        $min_annee = $request->getParameter('min_annee');
        $max_annee = $request->getParameter('max_annee');

        $liste = calculSituationCumulee::getSituation($titre, $min_mois, $max_mois, $min_annee, $max_annee);

        $titre_budget = TitrebudjetTable::getInstance()->find($titre);

        $commencee_au = '01/' . str_pad($min_mois, 2, 0, STR_PAD_LEFT) . '/' . $min_annee;

        $arretee_au = $max_annee . '-' . str_pad($max_mois, 2, 0, STR_PAD_LEFT) . '-01';
        $arretee_au = date('t/m/Y', strtotime($arretee_au));

        $html = '<h3 style="font-size:18px;">SITUATION CUMULEE DU PROJET<br><b style="font-size:12px;">Du : ' . $commencee_au . ' au : ' . $arretee_au . '</b></h3>';

        $html.='&nbsp;<br><div>
                    <table>
                        <tr>
                            <td style="width:100%;"><b>Budget :</b> ' . $titre_budget . '</td>
                        </tr>
                    </table>
                </div>';

        $html.='<table><tr><td style="text-align:right;width:100%;"><b>(en DT)</b></td></tr></table>
                <table border="1" cellpadding="3">
                    <tr style="font-size:10px;text-align:center;font-weight:bold;background-color:#E0E0E0;">
                        <td style="width:55%;">Rubriques</td>
                        <td style="width:15%;height:25px;">Engagements Cumulés</td>
                        <td style="width:15%;">Paiements Cumulés</td>
                        <td style="width:15%;">Engagements à Payer</td>
                    </tr>';

        $mnt_engagement = 0;
        $mnt_paiement = 0;

        for ($i = 0; $i < sizeof($liste); $i++):
            $html.='<tr style="font-size:10px;">
                        <td style="height:25px;">' . $liste[$i]['rubrique'] . '</td>
                        <td style="text-align:right;">' . number_format($liste[$i]['engagement'], 3, '.', ' ') . '</td>
                        <td style="text-align:right;">' . number_format($liste[$i]['paiement'], 3, '.', ' ') . '</td>
                        <td style="text-align:right;"><b>' . number_format($liste[$i]['total'], 3, '.', ' ') . '</b></td>
                </tr>';

            $mnt_engagement = $mnt_engagement + $liste[$i]['totalEngagement'];
            $mnt_paiement = $mnt_paiement + $liste[$i]['totalpaiement'];

        endfor;

        $html.='<tr style="font-size:10px;font-weight:bold;background-color:#E0E0E0;">
                        <td style="text-align:center;height:25px;">Total Général</td>
                        <td style="text-align:right;">' . number_format($mnt_engagement, 3, '.', ' ') . '</td>
                        <td style="text-align:right;">' . number_format($mnt_paiement, 3, '.', ' ') . '</td>
                        <td style="text-align:right;">' . number_format($mnt_engagement - $mnt_paiement, 3, '.', ' ') . '</td>
                </tr>';

        $html.='</table>';

        return $html;
    }

}
