<?php

/**
 * SourcesfinancemmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SourcesfinancemmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SourcesfinancemmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sourcesfinancemment');
    }
}