<?php

/**
 * SourcepretTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SourcepretTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SourcepretTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sourcepret');
    }
}