<?php

/**
 * SousdetailprixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SousdetailprixTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SousdetailprixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sousdetailprix');
    }
}