<?php

/**
 * Tableauxammortisement
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    InventaireTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tableauxammortisement extends BaseTableauxammortisement {

    public function getDotation1() {
        $dotation = number_format($this->getDotation(), 3);
        return $dotation;
    }

    public function getAmrtinterieur1() {
        $amrt = number_format($this->getAmrtinterieur(), 3);

        return $amrt;
    }

//amrtcumile

    public function getAmrtcumile1() {
        $amrtc = number_format($this->getAmrtcumile(), 3);
        return $amrtc;
    }

    public function getVcn1() {
        if ($this->getVcn()) {
            $vcn = number_format($this->getVcn(), 3);
            return $vcn;
        }return "0.000";
    }

    public function getDateaquisition1() {
        if ($this->getDateAquisition())
            return date("Y-m-d", strtotime($this->getDateAquisition()));
        return "";
    }

    public function ReadHtmlListe(sfWebRequest $request) {
        $id = $request->getParameter('id');
        $id_categorie = $request->getParameter('id_categorie');
        $id_famille = $request->getParameter('id_famille');
        $id_sousfamille = $request->getParameter('id_sousfamille');
        $annee = $request->getParameter('annee');

        $tableaux = TableauxammortisementTable::getInstance()->getForPrintList($id, $id_categorie, $id_famille, $id_sousfamille, $annee);
        ini_set('memory_limit', '-1');
        $html = '<h3 style="font-size:18px;">Tableaux Amortissement / Liste des Immobilisations</h3>
            &nbsp;<br>';

        $html.='<table border="1" cellspace="0" cellpadding="3">
                    <tr style="background-color:#ECECEC;">
                        <td style="width:6%;height:25px;text-align:center;">#</td>
                        <td style="width:33%;height:25px;text-align:center;"><b>Immobilisation</b></td>
                        <td style="width:9%;text-align:center;"><b>Date Acquisition</b></td>
                        <td style="width:9%;text-align:center;"><b>Valeur Origine</b></td>
                        <td style="width:7%;text-align:center;"><b>Taux</b></td>
                        <td style="width:9%;text-align:center;"><b>Dotation</b></td>
                        <td style="width:9%;text-align:center;"><b>Amorti. Antérieur</b></td>
                        <td style="width:9%;text-align:center;"><b>Amorti. Cumulé</b></td>
                        <td style="width:9%;text-align:center;"><b>VCN</b></td>
                    </tr>';

        if ($tableaux->count() != 0):
            $i = 1;
            foreach ($tableaux as $tableauxammortisement):
                $html.='<tr style="font-size:10px;">
                                <td style="width:6%;text-align:center;">' . $i . '</td>
                                <td style="width:33%;height:25px;">' . $tableauxammortisement->getImmobilisation() . '</td>
                                <td style="width:9%;text-align:center;">' . date('d/m/Y', strtotime($tableauxammortisement->getDateaquisition1())) . '</td>
                                <td style="width:9%;text-align:right;">' . number_format($tableauxammortisement->getVorigine(), 3, '.', ' ') . '</td>
                                <td style="width:7%;text-align:center;">' . number_format(floatval($tableauxammortisement->getTaux()), 2, '.') . ' %</td>
                                <td style="width:9%;text-align:right;">' . number_format($tableauxammortisement->getDotation1(), 3, '.', ' ') . '</td>
                                <td style="width:9%;text-align:right;">' . number_format($tableauxammortisement->getAmrtinterieur1(), 3, '.', ' ') . '</td>
                                <td style="width:9%;text-align:right;">' . number_format($tableauxammortisement->getAmrtcumile1(), 3, '.', ' ') . '</td>
                                <td style="width:9%;text-align:right;">' . number_format($tableauxammortisement->getVcn1(), 3, '.', ' ') . '</td>
                        </tr>';
                $i++;
            endforeach;
        else:
            $html.='<tr>
                        <td style="width:100%;height:20px;text-align:center;">Pas d\'immobilisations</td>
                    </tr>';
        endif;

        $html.='</table>';
        return $html;
    }

}
