<?php

/**
 * TravailrapporttravauxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TravailrapporttravauxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TravailrapporttravauxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Travailrapporttravaux');
    }
    
    public function getByRapport($id) {
        $q = Doctrine_Core::getTable('Travailrapporttravaux')
                ->createQuery('t')
                ->where('t.id_rapporttravaux = ?', $id)
                ->orderBy('t.id')
                ->execute();

        return $q;
    }
}