<?php

/**
 * TypeaideTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeaideTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeaideTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typeaide');
    }
}