<?php

/**
 * TypedocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypedocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypedocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typedoc');
    }
}