<?php

/**
 * TypedisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypedisciplineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypedisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typediscipline');
    }
}