<?php

/**
 * TypeoperationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeoperationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeoperationTable
     */
    public static function getInstance(){
        return Doctrine_Core::getTable('Typeoperation');
    }
    
    public function getForBordereauEspece() {
        $query = $this->createQuery('to');
        $query->select('to.*')
                ->from('Typeoperation to')
                ->where("to.codeop = 'VR-R' OR to.codeop = 'VR-E'")
                ->orderBy('to.libelle');
        return $query->execute();
    }
}