<?php

/**
 * TypedetailprixTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypedetailprixTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypedetailprixTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typedetailprix');
    }
}