<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Typetenue', 'doctrine');

/**
 * BaseTypetenue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property integer $id_typemisson
 * @property Typemission $Typemission
 * @property Doctrine_Collection $Tenues
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getLibelle()       Returns the current record's "libelle" value
 * @method integer             getIdTypemisson()  Returns the current record's "id_typemisson" value
 * @method Typemission         getTypemission()   Returns the current record's "Typemission" value
 * @method Doctrine_Collection getTenues()        Returns the current record's "Tenues" collection
 * @method Typetenue           setId()            Sets the current record's "id" value
 * @method Typetenue           setLibelle()       Sets the current record's "libelle" value
 * @method Typetenue           setIdTypemisson()  Sets the current record's "id_typemisson" value
 * @method Typetenue           setTypemission()   Sets the current record's "Typemission" value
 * @method Typetenue           setTenues()        Sets the current record's "Tenues" collection
 * 
 * @package    PhpProjecttest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypetenue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typetenue');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'typetenue_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_typemisson', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Typemission', array(
             'local' => 'id_typemisson',
             'foreign' => 'id'));

        $this->hasMany('Tenues', array(
             'local' => 'id',
             'foreign' => 'id_typetenue'));
    }
}