<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Naturecertif', 'doctrine');

/**
 * BaseNaturecertif
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property string $nbrjour
 * @property string $typetraitement
 * @property Doctrine_Collection $Certificat
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getLibelle()        Returns the current record's "libelle" value
 * @method string              getNbrjour()        Returns the current record's "nbrjour" value
 * @method string              getTypetraitement() Returns the current record's "typetraitement" value
 * @method Doctrine_Collection getCertificat()     Returns the current record's "Certificat" collection
 * @method Naturecertif        setId()             Sets the current record's "id" value
 * @method Naturecertif        setLibelle()        Sets the current record's "libelle" value
 * @method Naturecertif        setNbrjour()        Sets the current record's "nbrjour" value
 * @method Naturecertif        setTypetraitement() Sets the current record's "typetraitement" value
 * @method Naturecertif        setCertificat()     Sets the current record's "Certificat" collection
 * 
 * @package    PhpProjecttest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNaturecertif extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('naturecertif');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'naturecerif_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('nbrjour', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('typetraitement', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Certificat', array(
             'local' => 'id',
             'foreign' => 'id_naturecertif'));
    }
}