<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parametragetypedoc', 'doctrine');

/**
 * BaseParametragetypedoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_avis
 * @property integer $id_visa
 * @property integer $id_typedoc
 * @property Avis $Avis
 * @property Visaachat $Visaachat
 * @property Typedoc $Typedoc
 * 
 * @method integer            getId()         Returns the current record's "id" value
 * @method integer            getIdAvis()     Returns the current record's "id_avis" value
 * @method integer            getIdVisa()     Returns the current record's "id_visa" value
 * @method integer            getIdTypedoc()  Returns the current record's "id_typedoc" value
 * @method Avis               getAvis()       Returns the current record's "Avis" value
 * @method Visaachat          getVisaachat()  Returns the current record's "Visaachat" value
 * @method Typedoc            getTypedoc()    Returns the current record's "Typedoc" value
 * @method Parametragetypedoc setId()         Sets the current record's "id" value
 * @method Parametragetypedoc setIdAvis()     Sets the current record's "id_avis" value
 * @method Parametragetypedoc setIdVisa()     Sets the current record's "id_visa" value
 * @method Parametragetypedoc setIdTypedoc()  Sets the current record's "id_typedoc" value
 * @method Parametragetypedoc setAvis()       Sets the current record's "Avis" value
 * @method Parametragetypedoc setVisaachat()  Sets the current record's "Visaachat" value
 * @method Parametragetypedoc setTypedoc()    Sets the current record's "Typedoc" value
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParametragetypedoc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametragetypedoc');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'parametragetypedoc_id',
             'length' => 4,
             ));
        $this->hasColumn('id_avis', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_visa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_typedoc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Avis', array(
             'local' => 'id_avis',
             'foreign' => 'id'));

        $this->hasOne('Visaachat', array(
             'local' => 'id_visa',
             'foreign' => 'id'));

        $this->hasOne('Typedoc', array(
             'local' => 'id_typedoc',
             'foreign' => 'id'));
    }
}