<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ligneinventaire', 'doctrine');

/**
 * BaseLigneinventaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_inventaire
 * @property integer $id_article
 * @property decimal $qtereel
 * @property decimal $qtetheorique
 * @property decimal $ecartreel
 * @property decimal $ecartthorique
 * @property Inventairedoc $Inventairedoc
 * @property Article $Article
 * 
 * @method integer         getId()            Returns the current record's "id" value
 * @method integer         getIdInventaire()  Returns the current record's "id_inventaire" value
 * @method integer         getIdArticle()     Returns the current record's "id_article" value
 * @method decimal         getQtereel()       Returns the current record's "qtereel" value
 * @method decimal         getQtetheorique()  Returns the current record's "qtetheorique" value
 * @method decimal         getEcartreel()     Returns the current record's "ecartreel" value
 * @method decimal         getEcartthorique() Returns the current record's "ecartthorique" value
 * @method Inventairedoc   getInventairedoc() Returns the current record's "Inventairedoc" value
 * @method Article         getArticle()       Returns the current record's "Article" value
 * @method Ligneinventaire setId()            Sets the current record's "id" value
 * @method Ligneinventaire setIdInventaire()  Sets the current record's "id_inventaire" value
 * @method Ligneinventaire setIdArticle()     Sets the current record's "id_article" value
 * @method Ligneinventaire setQtereel()       Sets the current record's "qtereel" value
 * @method Ligneinventaire setQtetheorique()  Sets the current record's "qtetheorique" value
 * @method Ligneinventaire setEcartreel()     Sets the current record's "ecartreel" value
 * @method Ligneinventaire setEcartthorique() Sets the current record's "ecartthorique" value
 * @method Ligneinventaire setInventairedoc() Sets the current record's "Inventairedoc" value
 * @method Ligneinventaire setArticle()       Sets the current record's "Article" value
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLigneinventaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ligneinventaire');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'ligneinventaire_id',
             'length' => 4,
             ));
        $this->hasColumn('id_inventaire', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_article', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('qtereel', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qtetheorique', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('ecartreel', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('ecartthorique', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Inventairedoc', array(
             'local' => 'id_inventaire',
             'foreign' => 'id'));

        $this->hasOne('Article', array(
             'local' => 'id_article',
             'foreign' => 'id'));
    }
}