<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Recomposediscipline', 'doctrine');

/**
 * BaseRecomposediscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property string $source
 * @property string $explication
 * @property integer $id_agents
 * @property integer $id_typedecipline
 * @property Agents $Agents
 * @property Typediscpline $Typediscpline
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method date                getDate()             Returns the current record's "date" value
 * @method string              getSource()           Returns the current record's "source" value
 * @method string              getExplication()      Returns the current record's "explication" value
 * @method integer             getIdAgents()         Returns the current record's "id_agents" value
 * @method integer             getIdTypedecipline()  Returns the current record's "id_typedecipline" value
 * @method Agents              getAgents()           Returns the current record's "Agents" value
 * @method Typediscpline       getTypediscpline()    Returns the current record's "Typediscpline" value
 * @method Recomposediscipline setId()               Sets the current record's "id" value
 * @method Recomposediscipline setDate()             Sets the current record's "date" value
 * @method Recomposediscipline setSource()           Sets the current record's "source" value
 * @method Recomposediscipline setExplication()      Sets the current record's "explication" value
 * @method Recomposediscipline setIdAgents()         Sets the current record's "id_agents" value
 * @method Recomposediscipline setIdTypedecipline()  Sets the current record's "id_typedecipline" value
 * @method Recomposediscipline setAgents()           Sets the current record's "Agents" value
 * @method Recomposediscipline setTypediscpline()    Sets the current record's "Typediscpline" value
 * 
 * @package    PhpProjectTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecomposediscipline extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recomposediscipline');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => '"recomposeDiscipline_id_seq"',
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('source', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('explication', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_agents', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_typedecipline', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Agents', array(
             'local' => 'id_agents',
             'foreign' => 'id'));

        $this->hasOne('Typediscpline', array(
             'local' => 'id_typedecipline',
             'foreign' => 'id'));
    }
}