<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Typemission', 'doctrine');

/**
 * BaseTypemission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property Doctrine_Collection $Typetenue
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getLibelle()   Returns the current record's "libelle" value
 * @method Doctrine_Collection getTypetenue() Returns the current record's "Typetenue" collection
 * @method Typemission         setId()        Sets the current record's "id" value
 * @method Typemission         setLibelle()   Sets the current record's "libelle" value
 * @method Typemission         setTypetenue() Sets the current record's "Typetenue" collection
 * 
 * @package    PhpProjecttest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypemission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typemission');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'typemission_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Typetenue', array(
             'local' => 'id',
             'foreign' => 'id_typemisson'));
    }
}