<?php

/**
 * BaseSourceMarcheprevesionelle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string                                     $name                                            Type: string
 * @property serial                                     $id                                              Type: serial, primary key
 * @property Doctrine_Collection|MarchePrevesionelle[]  $MarchePrevesionelle                             
 *  
 * @method string                                       getName()                                        Type: string
 * @method serial                                       getId()                                          Type: serial, primary key
 * @method Doctrine_Collection|MarchePrevesionelle[]    getMarchePrevesionelle()                         
 *  
 * @method SourceMarcheprevesionelle                    setName(string $val)                             Type: string
 * @method SourceMarcheprevesionelle                    setId(serial $val)                               Type: serial, primary key
 * @method SourceMarcheprevesionelle                    setMarchePrevesionelle(Doctrine_Collection $val) 
 *  
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSourceMarcheprevesionelle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('source_marcheprevesionelle');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('id', 'serial', null, array(
             'type' => 'serial',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
            
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MarchePrevesionelle', array(
             'local' => 'id',
             'foreign' => 'id_sources'));
    }
}