<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tauxfodec', 'doctrine');

/**
 * BaseTauxfodec
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property integer $valeur
 * @property string $libelle
 * @property Doctrine_Collection $Contratachat
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getCode()         Returns the current record's "code" value
 * @method integer             getValeur()       Returns the current record's "valeur" value
 * @method string              getLibelle()      Returns the current record's "libelle" value
 * @method Doctrine_Collection getContratachat() Returns the current record's "Contratachat" collection
 * @method Tauxfodec           setId()           Sets the current record's "id" value
 * @method Tauxfodec           setCode()         Sets the current record's "code" value
 * @method Tauxfodec           setValeur()       Sets the current record's "valeur" value
 * @method Tauxfodec           setLibelle()      Sets the current record's "libelle" value
 * @method Tauxfodec           setContratachat() Sets the current record's "Contratachat" collection
 * 
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTauxfodec extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tauxfodec');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tauxfodec_id',
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('valeur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contratachat', array(
             'local' => 'id',
             'foreign' => 'id_tauxfodec'));
    }
}