<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menus', 'doctrine');

/**
 * BaseMenus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
* @property string $menu
 * @property string $name
 * @property string $link
 * @property integer $id_parent
 * @property string $icon
 * @property string $classicon
 * @property Doctrine_Collection $Menus
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getOrdre()      Returns the current record's "odre" value
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getLink()      Returns the current record's "link" value
 * @method integer             getIdParent()  Returns the current record's "id_parent" value
 * @method string              getIcon()      Returns the current record's "icon" value
 * @method string              getClassicon()      Returns the current record's "classicon" value
 * @method Doctrine_Collection getMenus()     Returns the current record's "Menus" collection
 * @method Menus               setId()        Sets the current record's "id" value
 * @method Menus               setOrdre()      Sets the current record's "ordre" value
 * @method Menus               setName()      Sets the current record's "name" value
 * @method Menus               setLink()      Sets the current record's "link" value
 * @method Menus               setIdParent()  Sets the current record's "id_parent" value
 * @method Menus               setIcon()      Sets the current record's "icon" value
 * @method Menus               setClassicon()      Sets the current record's "classicon" value
 * @method Menus               setMenus()     Sets the current record's "Menus" collection
 * 
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menus');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'menus_id',
             'length' => 4,
             ));
        $this->hasColumn('ordre', 'string', 4, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
        $this->hasColumn('link', 'string', 254, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 254,
             ));
        $this->hasColumn('id_parent', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 5,
             ));
        $this->hasColumn('icon', 'string', 254, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 254,
             ));
        $this->hasColumn('classicon', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Menus', array(
             'local' => 'id',
             'foreign' => 'id_parent'));
    }
}