<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Financement', 'doctrine');

/**
 * BaseFinancement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $mntht
 * @property decimal $tauxtva
 * @property decimal $mntttc
 * @property decimal $mnttva
 * @property string $caracteristiqueprix
 * @property string $natureprix
 * @property integer $id_lignebudget
 * @property integer $id_marche
 * @property integer $id_tva
 * @property Ligprotitrub $Ligprotitrub
 * @property Marches $Marches
 * @property Tva $Tva
 * 
 * @method integer      getId()                  Returns the current record's "id" value
 * @method decimal      getMntht()               Returns the current record's "mntht" value
 * @method decimal      getTauxtva()             Returns the current record's "tauxtva" value
 * @method decimal      getMntttc()              Returns the current record's "mntttc" value
 * @method decimal      getMnttva()              Returns the current record's "mnttva" value
 * @method string       getCaracteristiqueprix() Returns the current record's "caracteristiqueprix" value
 * @method string       getNatureprix()          Returns the current record's "natureprix" value
 * @method integer      getIdLignebudget()       Returns the current record's "id_lignebudget" value
 * @method integer      getIdMarche()            Returns the current record's "id_marche" value
 * @method integer      getIdTva()               Returns the current record's "id_tva" value
 * @method Ligprotitrub getLigprotitrub()        Returns the current record's "Ligprotitrub" value
 * @method Marches      getMarches()             Returns the current record's "Marches" value
 * @method Tva          getTva()                 Returns the current record's "Tva" value
 * @method Financement  setId()                  Sets the current record's "id" value
 * @method Financement  setMntht()               Sets the current record's "mntht" value
 * @method Financement  setTauxtva()             Sets the current record's "tauxtva" value
 * @method Financement  setMntttc()              Sets the current record's "mntttc" value
 * @method Financement  setMnttva()              Sets the current record's "mnttva" value
 * @method Financement  setCaracteristiqueprix() Sets the current record's "caracteristiqueprix" value
 * @method Financement  setNatureprix()          Sets the current record's "natureprix" value
 * @method Financement  setIdLignebudget()       Sets the current record's "id_lignebudget" value
 * @method Financement  setIdMarche()            Sets the current record's "id_marche" value
 * @method Financement  setIdTva()               Sets the current record's "id_tva" value
 * @method Financement  setLigprotitrub()        Sets the current record's "Ligprotitrub" value
 * @method Financement  setMarches()             Sets the current record's "Marches" value
 * @method Financement  setTva()                 Sets the current record's "Tva" value
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFinancement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('financement');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'financement_id',
             'length' => 4,
             ));
        $this->hasColumn('mntht', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('tauxtva', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('mntttc', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('mnttva', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('caracteristiqueprix', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('natureprix', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 30,
             ));
        $this->hasColumn('id_lignebudget', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_marche', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tva', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ligprotitrub', array(
             'local' => 'id_lignebudget',
             'foreign' => 'id'));

        $this->hasOne('Marches', array(
             'local' => 'id_marche',
             'foreign' => 'id'));

        $this->hasOne('Tva', array(
             'local' => 'id_tva',
             'foreign' => 'id'));
    }
}