<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Souscomptejournal', 'doctrine');

/**
 * BaseSouscomptejournal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_souscompte
 * @property integer $id_journal
 * @property integer $isbloque
 * @property integer $isautorise
 * @property integer $isdebit
 * @property integer $iscredit
 * @property Plancomptable $Plancomptable
 * @property Journalcomptable $Journalcomptable
 * 
 * @method integer           getId()               Returns the current record's "id" value
 * @method integer           getIdSouscompte()     Returns the current record's "id_souscompte" value
 * @method integer           getIdJournal()        Returns the current record's "id_journal" value
 * @method integer           getIsbloque()         Returns the current record's "isbloque" value
 * @method integer           getIsautorise()       Returns the current record's "isautorise" value
 * @method integer           getIsdebit()          Returns the current record's "isdebit" value
 * @method integer           getIscredit()         Returns the current record's "iscredit" value
 * @method Plancomptable     getPlancomptable()    Returns the current record's "Plancomptable" value
 * @method Journalcomptable  getJournalcomptable() Returns the current record's "Journalcomptable" value
 * @method Souscomptejournal setId()               Sets the current record's "id" value
 * @method Souscomptejournal setIdSouscompte()     Sets the current record's "id_souscompte" value
 * @method Souscomptejournal setIdJournal()        Sets the current record's "id_journal" value
 * @method Souscomptejournal setIsbloque()         Sets the current record's "isbloque" value
 * @method Souscomptejournal setIsautorise()       Sets the current record's "isautorise" value
 * @method Souscomptejournal setIsdebit()          Sets the current record's "isdebit" value
 * @method Souscomptejournal setIscredit()         Sets the current record's "iscredit" value
 * @method Souscomptejournal setPlancomptable()    Sets the current record's "Plancomptable" value
 * @method Souscomptejournal setJournalcomptable() Sets the current record's "Journalcomptable" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSouscomptejournal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('souscomptejournal');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'souscomptejournal_id',
             'length' => 4,
             ));
        $this->hasColumn('id_souscompte', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_journal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('isbloque', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('isautorise', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('isdebit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('iscredit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Plancomptable', array(
             'local' => 'id_souscompte',
             'foreign' => 'id'));

        $this->hasOne('Journalcomptable', array(
             'local' => 'id_journal',
             'foreign' => 'id'));
    }
}