<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Adresse', 'doctrine');

/**
 * BaseAdresse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $adresse
 * @property integer $id_couvernera
 * @property string $codepostal
 * @property Doctrine_Collection $Gouvernera
 * @property Doctrine_Collection $Site
 * @property Doctrine_Collection $Agents
 * @property Doctrine_Collection $Documentachat
 * @property Doctrine_Collection $Fournisseur
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getAdresse()       Returns the current record's "adresse" value
 * @method integer             getIdCouvernera()  Returns the current record's "id_couvernera" value
 * @method string              getCodepostal()    Returns the current record's "codepostal" value
 * @method Doctrine_Collection getGouvernera()    Returns the current record's "Gouvernera" collection
 * @method Doctrine_Collection getSite()          Returns the current record's "Site" collection
 * @method Doctrine_Collection getAgents()        Returns the current record's "Agents" collection
 * @method Doctrine_Collection getDocumentachat() Returns the current record's "Documentachat" collection
 * @method Doctrine_Collection getFournisseur()   Returns the current record's "Fournisseur" collection
 * @method Adresse             setId()            Sets the current record's "id" value
 * @method Adresse             setAdresse()       Sets the current record's "adresse" value
 * @method Adresse             setIdCouvernera()  Sets the current record's "id_couvernera" value
 * @method Adresse             setCodepostal()    Sets the current record's "codepostal" value
 * @method Adresse             setGouvernera()    Sets the current record's "Gouvernera" collection
 * @method Adresse             setSite()          Sets the current record's "Site" collection
 * @method Adresse             setAgents()        Sets the current record's "Agents" collection
 * @method Adresse             setDocumentachat() Sets the current record's "Documentachat" collection
 * @method Adresse             setFournisseur()   Sets the current record's "Fournisseur" collection
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdresse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adresse');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'adresse_id',
             'length' => 4,
             ));
        $this->hasColumn('adresse', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_couvernera', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codepostal', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Gouvernera', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('Site', array(
             'local' => 'id',
             'foreign' => 'id_adresse'));

       

        $this->hasMany('Documentachat', array(
             'local' => 'id',
             'foreign' => 'id_adresse'));

        $this->hasMany('Fournisseur', array(
             'local' => 'id',
             'foreign' => 'id_adresse'));
    }
}