<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mouvementcomptable', 'doctrine');

/**
 * BaseMouvementcomptable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property string $reference
 * @property decimal $montant
 * @property date $dateimportation
 * @property integer $saisie
 * @property integer $id_piececomptable
 * @property integer $numero
 * @property date $datevaleur
 * @property string $libelle
 * @property integer $id_comptecomptable
 * @property integer $id_dossier
 * @property Plandossiercomptable $Plandossiercomptable
 * @property Dossiercomptable $Dossiercomptable
 * @property Piececomptable $Piececomptable
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method date                 getDate()                 Returns the current record's "date" value
 * @method string               getReference()            Returns the current record's "reference" value
 * @method decimal              getMontant()              Returns the current record's "montant" value
 * @method date                 getDateimportation()      Returns the current record's "dateimportation" value
 * @method integer              getSaisie()               Returns the current record's "saisie" value
 * @method integer              getIdPiececomptable()     Returns the current record's "id_piececomptable" value
 * @method integer              getNumero()               Returns the current record's "numero" value
 * @method date                 getDatevaleur()           Returns the current record's "datevaleur" value
 * @method string               getLibelle()              Returns the current record's "libelle" value
 * @method integer              getIdComptecomptable()    Returns the current record's "id_comptecomptable" value
 * @method integer              getIdDossier()            Returns the current record's "id_dossier" value
 * @method Plandossiercomptable getPlandossiercomptable() Returns the current record's "Plandossiercomptable" value
 * @method Dossiercomptable     getDossiercomptable()     Returns the current record's "Dossiercomptable" value
 * @method Piececomptable       getPiececomptable()       Returns the current record's "Piececomptable" value
 * @method Mouvementcomptable   setId()                   Sets the current record's "id" value
 * @method Mouvementcomptable   setDate()                 Sets the current record's "date" value
 * @method Mouvementcomptable   setReference()            Sets the current record's "reference" value
 * @method Mouvementcomptable   setMontant()              Sets the current record's "montant" value
 * @method Mouvementcomptable   setDateimportation()      Sets the current record's "dateimportation" value
 * @method Mouvementcomptable   setSaisie()               Sets the current record's "saisie" value
 * @method Mouvementcomptable   setIdPiececomptable()     Sets the current record's "id_piececomptable" value
 * @method Mouvementcomptable   setNumero()               Sets the current record's "numero" value
 * @method Mouvementcomptable   setDatevaleur()           Sets the current record's "datevaleur" value
 * @method Mouvementcomptable   setLibelle()              Sets the current record's "libelle" value
 * @method Mouvementcomptable   setIdComptecomptable()    Sets the current record's "id_comptecomptable" value
 * @method Mouvementcomptable   setIdDossier()            Sets the current record's "id_dossier" value
 * @method Mouvementcomptable   setPlandossiercomptable() Sets the current record's "Plandossiercomptable" value
 * @method Mouvementcomptable   setDossiercomptable()     Sets the current record's "Dossiercomptable" value
 * @method Mouvementcomptable   setPiececomptable()       Sets the current record's "Piececomptable" value
 * 
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMouvementcomptable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mouvementcomptable ');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => '"mouvementcomptable _id_seq"',
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('reference', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('montant', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('dateimportation', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('saisie', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 2,
             ));
        $this->hasColumn('id_piececomptable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('datevaleur', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('libelle', 'string', 25, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_comptecomptable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_dossier', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Plandossiercomptable', array(
             'local' => 'id_comptecomptable',
             'foreign' => 'id'));

        $this->hasOne('Dossiercomptable', array(
             'local' => 'id_dossier',
             'foreign' => 'id'));

        $this->hasOne('Piececomptable', array(
             'local' => 'id_piececomptable',
             'foreign' => 'id'));
    }
}