<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Typeios', 'doctrine');

/**
 * BaseTypeios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property Doctrine_Collection $Ordredeservice
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getLibelle()        Returns the current record's "libelle" value
 * @method Doctrine_Collection getOrdredeservice() Returns the current record's "Ordredeservice" collection
 * @method Typeios             setId()             Sets the current record's "id" value
 * @method Typeios             setLibelle()        Sets the current record's "libelle" value
 * @method Typeios             setOrdredeservice() Sets the current record's "Ordredeservice" collection
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typeios');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'typeios_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 254, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 254,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ordredeservice', array(
             'local' => 'id',
             'foreign' => 'id_type'));
    }
}