<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Niveauxage', 'doctrine');

/**
 * BaseNiveauxage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property integer $intervaldebut
 * @property integer $intervalfin
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method string     getLibelle()       Returns the current record's "libelle" value
 * @method integer    getIntervaldebut() Returns the current record's "intervaldebut" value
 * @method integer    getIntervalfin()   Returns the current record's "intervalfin" value
 * @method Niveauxage setId()            Sets the current record's "id" value
 * @method Niveauxage setLibelle()       Sets the current record's "libelle" value
 * @method Niveauxage setIntervaldebut() Sets the current record's "intervaldebut" value
 * @method Niveauxage setIntervalfin()   Sets the current record's "intervalfin" value
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNiveauxage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('niveauxage');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'niveauxage_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 50,
             ));
        $this->hasColumn('intervaldebut', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('intervalfin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}