<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Demandedevoirfichieradmin', 'doctrine');

/**
 * BaseDemandedevoirfichieradmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_agents
 * @property integer $id_service
 * @property string $document
 * @property date $datedevue
 * @property integer $id_copie
 * @property string $personne
 * @property string $signatureagents
 * @property string $signaturedirecteur
 * @property string $cheminagents
 * @property string $chemindirecteu
 * @property integer $id_demandeur
 * @property Agents $Agents
 * @property Servicerh $Servicerh
 * @property Agents $Agents_3
 * @property Doctrine_Collection $Lignedemandecopie
 * 
 * @method integer                   getId()                 Returns the current record's "id" value
 * @method integer                   getIdAgents()           Returns the current record's "id_agents" value
 * @method integer                   getIdService()          Returns the current record's "id_service" value
 * @method string                    getDocument()           Returns the current record's "document" value
 * @method date                      getDatedevue()          Returns the current record's "datedevue" value
 * @method integer                   getIdCopie()            Returns the current record's "id_copie" value
 * @method string                    getPersonne()           Returns the current record's "personne" value
 * @method string                    getSignatureagents()    Returns the current record's "signatureagents" value
 * @method string                    getSignaturedirecteur() Returns the current record's "signaturedirecteur" value
 * @method string                    getCheminagents()       Returns the current record's "cheminagents" value
 * @method string                    getChemindirecteu()     Returns the current record's "chemindirecteu" value
 * @method integer                   getIdDemandeur()        Returns the current record's "id_demandeur" value
 * @method Agents                    getAgents()             Returns the current record's "Agents" value
 * @method Servicerh                 getServicerh()          Returns the current record's "Servicerh" value
 * @method Agents                    getAgents3()            Returns the current record's "Agents_3" value
 * @method Doctrine_Collection       getLignedemandecopie()  Returns the current record's "Lignedemandecopie" collection
 * @method Demandedevoirfichieradmin setId()                 Sets the current record's "id" value
 * @method Demandedevoirfichieradmin setIdAgents()           Sets the current record's "id_agents" value
 * @method Demandedevoirfichieradmin setIdService()          Sets the current record's "id_service" value
 * @method Demandedevoirfichieradmin setDocument()           Sets the current record's "document" value
 * @method Demandedevoirfichieradmin setDatedevue()          Sets the current record's "datedevue" value
 * @method Demandedevoirfichieradmin setIdCopie()            Sets the current record's "id_copie" value
 * @method Demandedevoirfichieradmin setPersonne()           Sets the current record's "personne" value
 * @method Demandedevoirfichieradmin setSignatureagents()    Sets the current record's "signatureagents" value
 * @method Demandedevoirfichieradmin setSignaturedirecteur() Sets the current record's "signaturedirecteur" value
 * @method Demandedevoirfichieradmin setCheminagents()       Sets the current record's "cheminagents" value
 * @method Demandedevoirfichieradmin setChemindirecteu()     Sets the current record's "chemindirecteu" value
 * @method Demandedevoirfichieradmin setIdDemandeur()        Sets the current record's "id_demandeur" value
 * @method Demandedevoirfichieradmin setAgents()             Sets the current record's "Agents" value
 * @method Demandedevoirfichieradmin setServicerh()          Sets the current record's "Servicerh" value
 * @method Demandedevoirfichieradmin setAgents3()            Sets the current record's "Agents_3" value
 * @method Demandedevoirfichieradmin setLignedemandecopie()  Sets the current record's "Lignedemandecopie" collection
 * 
 * @package    PhpProjecttest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemandedevoirfichieradmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demandedevoirfichieradmin');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
            'sequence' => 'demandedevoirfichieradmin_id',
             'length' => 4,
             ));
        $this->hasColumn('id_agents', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_service', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('document', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('datedevue', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_copie', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('personne', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('signatureagents', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('signaturedirecteur', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('cheminagents', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('chemindirecteu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_demandeur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Agents', array(
             'local' => 'id_agents',
             'foreign' => 'id'));

        $this->hasOne('Servicerh', array(
             'local' => 'id_service',
             'foreign' => 'id'));

        $this->hasOne('Agents as Agents_3', array(
             'local' => 'id_demandeur',
             'foreign' => 'id'));

        $this->hasMany('Lignedemandecopie', array(
             'local' => 'id',
             'foreign' => 'id_demande'));
    }
}