<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Droittimbre', 'doctrine');

/**
 * BaseDroittimbre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property decimal $valeur
 * @property Doctrine_Collection $Documentachat
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getLibelle()       Returns the current record's "libelle" value
 * @method decimal             getValeur()        Returns the current record's "valeur" value
 * @method Doctrine_Collection getDocumentachat() Returns the current record's "Documentachat" collection
 * @method Droittimbre         setId()            Sets the current record's "id" value
 * @method Droittimbre         setLibelle()       Sets the current record's "libelle" value
 * @method Droittimbre         setValeur()        Sets the current record's "valeur" value
 * @method Droittimbre         setDocumentachat() Sets the current record's "Documentachat" collection
 * 
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDroittimbre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('droittimbre');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'droittimbre_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('valeur', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => 'NULL::numeric',
             'primary' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Documentachat', array(
             'local' => 'id',
             'foreign' => 'id_droittimbre'));
    }
}