<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ligneattestationouvrier', 'doctrine');

/**
 * BaseLigneattestationouvrier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_ouvrier
 * @property integer $id_attestation
 * @property integer $nordre
 * @property Ouvrier $Ouvrier
 * @property Attestationouvrier $Attestationouvrier
 * 
 * @method integer                 getId()                 Returns the current record's "id" value
 * @method integer                 getIdOuvrier()          Returns the current record's "id_ouvrier" value
 * @method integer                 getIdAttestation()      Returns the current record's "id_attestation" value
 * @method integer                 getNordre()             Returns the current record's "nordre" value
 * @method Ouvrier                 getOuvrier()            Returns the current record's "Ouvrier" value
 * @method Attestationouvrier      getAttestationouvrier() Returns the current record's "Attestationouvrier" value
 * @method Ligneattestationouvrier setId()                 Sets the current record's "id" value
 * @method Ligneattestationouvrier setIdOuvrier()          Sets the current record's "id_ouvrier" value
 * @method Ligneattestationouvrier setIdAttestation()      Sets the current record's "id_attestation" value
 * @method Ligneattestationouvrier setNordre()             Sets the current record's "nordre" value
 * @method Ligneattestationouvrier setOuvrier()            Sets the current record's "Ouvrier" value
 * @method Ligneattestationouvrier setAttestationouvrier() Sets the current record's "Attestationouvrier" value
 * 
 * @package    PhpProjectTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLigneattestationouvrier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ligneattestationouvrier');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'ligneattestationouvrier_id',
             'length' => 4,
             ));
        $this->hasColumn('id_ouvrier', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_attestation', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('nordre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ouvrier', array(
             'local' => 'id_ouvrier',
             'foreign' => 'id'));

        $this->hasOne('Attestationouvrier', array(
             'local' => 'id_attestation',
             'foreign' => 'id'));
    }
}