<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dossierexerciceutilisateur', 'doctrine');

/**
 * BaseDossierexerciceutilisateur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property integer $id_utilisateur
 * @property integer $id_dossierexercice
 * @property Dossierexercice $Dossierexercice
 * @property Utilisateur $Utilisateur
 * 
 * @method integer                    getId()                 Returns the current record's "id" value
 * @method date                       getDate()               Returns the current record's "date" value
 * @method integer                    getIdUtilisateur()      Returns the current record's "id_utilisateur" value
 * @method integer                    getIdDossierexercice()  Returns the current record's "id_dossierexercice" value
 * @method Dossierexercice            getDossierexercice()    Returns the current record's "Dossierexercice" value
 * @method Utilisateur                getUtilisateur()        Returns the current record's "Utilisateur" value
 * @method Dossierexerciceutilisateur setId()                 Sets the current record's "id" value
 * @method Dossierexerciceutilisateur setDate()               Sets the current record's "date" value
 * @method Dossierexerciceutilisateur setIdUtilisateur()      Sets the current record's "id_utilisateur" value
 * @method Dossierexerciceutilisateur setIdDossierexercice()  Sets the current record's "id_dossierexercice" value
 * @method Dossierexerciceutilisateur setDossierexercice()    Sets the current record's "Dossierexercice" value
 * @method Dossierexerciceutilisateur setUtilisateur()        Sets the current record's "Utilisateur" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDossierexerciceutilisateur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dossierexerciceutilisateur');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'dossierexerciceutilisateur_id',
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_dossierexercice', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dossierexercice', array(
             'local' => 'id_dossierexercice',
             'foreign' => 'id'));

        $this->hasOne('Utilisateur', array(
             'local' => 'id_utilisateur',
             'foreign' => 'id'));
    }
}