<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Qtelignedoc', 'doctrine');

/**
 * BaseQtelignedoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $qtees
 * @property decimal $qteep
 * @property decimal $qteas
 * @property decimal $qteap
 * @property decimal $qteaachat
 * @property decimal $qteeachat
 * @property decimal $qtelivrefrs
 * @property integer $id_lignedocachat
 * @property decimal $qtedemander
 * @property Lignedocachat $Lignedocachat
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method decimal       getQtees()            Returns the current record's "qtees" value
 * @method decimal       getQteep()            Returns the current record's "qteep" value
 * @method decimal       getQteas()            Returns the current record's "qteas" value
 * @method decimal       getQteap()            Returns the current record's "qteap" value
 * @method decimal       getQteaachat()        Returns the current record's "qteaachat" value
 * @method decimal       getQteeachat()        Returns the current record's "qteeachat" value
 * @method decimal       getQtelivrefrs()      Returns the current record's "qtelivrefrs" value
 * @method integer       getIdLignedocachat()  Returns the current record's "id_lignedocachat" value
 * @method decimal       getQtedemander()      Returns the current record's "qtedemander" value
 * @method Lignedocachat getLignedocachat()    Returns the current record's "Lignedocachat" value
 * @method Qtelignedoc   setId()               Sets the current record's "id" value
 * @method Qtelignedoc   setQtees()            Sets the current record's "qtees" value
 * @method Qtelignedoc   setQteep()            Sets the current record's "qteep" value
 * @method Qtelignedoc   setQteas()            Sets the current record's "qteas" value
 * @method Qtelignedoc   setQteap()            Sets the current record's "qteap" value
 * @method Qtelignedoc   setQteaachat()        Sets the current record's "qteaachat" value
 * @method Qtelignedoc   setQteeachat()        Sets the current record's "qteeachat" value
 * @method Qtelignedoc   setQtelivrefrs()      Sets the current record's "qtelivrefrs" value
 * @method Qtelignedoc   setIdLignedocachat()  Sets the current record's "id_lignedocachat" value
 * @method Qtelignedoc   setQtedemander()      Sets the current record's "qtedemander" value
 * @method Qtelignedoc   setLignedocachat()    Sets the current record's "Lignedocachat" value
 * 
 * @package    BmmErpTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQtelignedoc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('qtelignedoc');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'qtelignedoc_id',
             'length' => 4,
             ));
        $this->hasColumn('qtees', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qteep', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qteas', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qteap', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qteaachat', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qteeachat', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('qtelivrefrs', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('id_lignedocachat', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('qtedemander', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lignedocachat', array(
             'local' => 'id_lignedocachat',
             'foreign' => 'id'));
    }
}