<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Lignecodesociale', 'doctrine');

/**
 * BaseLignecodesociale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_codesoc
 * @property integer $nordre
 * @property string $libelle
 * @property decimal $taux
 * @property integer $code
 * @property Codesociale $Codesociale
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method integer          getIdCodesoc()   Returns the current record's "id_codesoc" value
 * @method integer          getNordre()      Returns the current record's "nordre" value
 * @method string           getLibelle()     Returns the current record's "libelle" value
 * @method decimal          getTaux()        Returns the current record's "taux" value
 * @method integer          getCode()        Returns the current record's "code" value
 * @method Codesociale      getCodesociale() Returns the current record's "Codesociale" value
 * @method Lignecodesociale setId()          Sets the current record's "id" value
 * @method Lignecodesociale setIdCodesoc()   Sets the current record's "id_codesoc" value
 * @method Lignecodesociale setNordre()      Sets the current record's "nordre" value
 * @method Lignecodesociale setLibelle()     Sets the current record's "libelle" value
 * @method Lignecodesociale setTaux()        Sets the current record's "taux" value
 * @method Lignecodesociale setCode()        Sets the current record's "code" value
 * @method Lignecodesociale setCodesociale() Sets the current record's "Codesociale" value
 * 
 * @package    Tes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLignecodesociale extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lignecodesociale');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'lignecodesociale_id',
             'length' => 4,
             ));
        $this->hasColumn('id_codesoc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('nordre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('taux', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Codesociale', array(
             'local' => 'id_codesoc',
             'foreign' => 'id'));
    }
}