<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Domaineuntilisation', 'doctrine');

/**
 * BaseDomaineuntilisation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $libelle
 * @property integer $code
 * @property Doctrine_Collection $Rubriqueformation
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getLibelle()           Returns the current record's "libelle" value
 * @method integer             getCode()              Returns the current record's "code" value
 * @method Doctrine_Collection getRubriqueformation() Returns the current record's "Rubriqueformation" collection
 * @method Domaineuntilisation setId()                Sets the current record's "id" value
 * @method Domaineuntilisation setLibelle()           Sets the current record's "libelle" value
 * @method Domaineuntilisation setCode()              Sets the current record's "code" value
 * @method Domaineuntilisation setRubriqueformation() Sets the current record's "Rubriqueformation" collection
 * 
 * @package    PhpProjectTest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDomaineuntilisation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domaineuntilisation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'domaineuntilisation_id',
             'length' => 4,
             ));
        $this->hasColumn('libelle', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rubriqueformation', array(
             'local' => 'id',
             'foreign' => 'id_domaine'));
    }
}