<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Modescourrier', 'doctrine');

/**
 * BaseModescourrier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mode
 * @property Doctrine_Collection $Courrier
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getMode()     Returns the current record's "mode" value
 * @method Doctrine_Collection getCourrier() Returns the current record's "Courrier" collection
 * @method Modescourrier       setId()       Sets the current record's "id" value
 * @method Modescourrier       setMode()     Sets the current record's "mode" value
 * @method Modescourrier       setCourrier() Sets the current record's "Courrier" collection
 * 
 * @package    Bmm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseModescourrier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('modescourrier');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('mode', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Courrier', array(
             'local' => 'id',
             'foreign' => 'id_mode'));
    }
}