generator:
  class: sfDoctrineGenerator
  param:
    model_class:           modeammortisement
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          modeammortisement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        modeammortisement: {label: "Mode d'amortissement"}
      list:
        title: Liste des Modes d'amortissement
        display: [modeammortisement]
        max_per_page: 5
      filter:  ~
      form:    ~
      edit:
        title: Modifier %%modeammortisement%%
      new:
        title: Nouveau mode d'amortissement
