generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sourcesbudget
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sourcesbudget
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: {}
      fields:  ~
      list:    
          title: Liste des sources de budget
          display: [source]
          object_actions: {}
          batch_actions: {}
          actions: {}
      filter:  ~
      form:    ~
      edit:    
        title: Mise à jour %%source%%
      new:     
        title: Nouveau source  
