generator:
  class: sfDoctrineGenerator
  param:
    model_class:           accidents
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          accidents
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      fields:  
          raison : { label: "Raison"}
          date : { label: "Date"}
          adresse : { label: "Adresse"}
          id_agents : {label: "Agents"}
      list:    
          title: Liste des Accidents
          display: [id_agents,raison,adresse]
      filter: 
          display: [id_agents,raison,adresse]
          
      form:    ~
      edit:    
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche 
