generator:
  class: sfDoctrineGenerator
  param:
    model_class:           procedurepassation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          procedurepassation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          libelle: { label: "Procédure"}
      list:
          title: Liste des procédures de passation
          display: [libelle]
      filter:  ~
      form:    ~
      edit:
          title: Mise à jour procédure de passation -%%libelle%%
      new:
          title: Nouvelle procédure de passation
