generator:
  class: sfDoctrineGenerator
  param:
    model_class:           parametragetranche
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          parametragetranche
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle: { label: "Nom du tranche"}
      list:    
          title: Liste de paramétrages du tranches
          display: [libelle]
      filter:  ~
      form:    ~
      edit:    
          title: Mise à jour fiche de paramétrage du tranche %%libelle%%
      new:     
          title: Nouvelle fiche de paramétrage du tranche
