generator:
  class: sfDoctrineGenerator
  param:
    model_class:           inventairestock
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          inventairestock
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_mag: { label : "Magasin"}
          datedepart: { label: "Date départ"}
          datefermeture: { label: "Date fermeture"}         
            
      list:  
          title: Listes des Inventaire
          display: [ magasin,datedepart,datefermeture]
          actions: {}          
          batch_actions: {}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
