generator:
  class: sfDoctrineGenerator
  param:
    model_class:           langues
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          langues
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          libelle : { label: "Libellé"}
      list:    
          title: Liste des langues
          display : [libelle]
      filter:  ~
      form:    ~
      edit:   
          title: Mise à jour fiche
      new:     
          title: Nouvelle fiche
