inventairestock:
  class: sfDoctrineRouteCollection
  options:
    model:                inventairestock
    module:               inventairestock
    prefix_path:          /inventairestock
    column:               id
    with_wildcard_routes: true

naturearticle:
  class: sfDoctrineRouteCollection
  options:
    model:                naturearticle
    module:               naturearticle
    prefix_path:          /naturearticle
    column:               id
    with_wildcard_routes: true
familleartfrs:
  class: sfDoctrineRouteCollection
  options:
    model:                familleartfrs
    module:               familleartfrs
    prefix_path:          /familleartfrs
    column:               id
    with_wildcard_routes: true
activitetiers:
  class: sfDoctrineRouteCollection
  options:
    model:                activitetiers
    module:               activitetiers
    prefix_path:          /activitetiers
    column:               id
    with_wildcard_routes: true

adressefrs:
  class: sfDoctrineRouteCollection
  options:
    model:                adressefrs
    module:               adressefrs
    prefix_path:          /adressefrs
    column:               id
    with_wildcard_routes: true

fournisseur:
  class: sfDoctrineRouteCollection
  options:
    model:                fournisseur
    module:               fournisseur
    prefix_path:          /fournisseur
    column:               id
    with_wildcard_routes: true
lignecararticle:
  class: sfDoctrineRouteCollection
  options:
    model:                lignecararticle
    module:               lignecararticle
    prefix_path:          /lignecararticle
    column:               id
    with_wildcard_routes: true

caracteristiquearticle:
  class: sfDoctrineRouteCollection
  options:
    model:                caracteristiquearticle
    module:               caracteristiquearticle
    prefix_path:          /caracteristiquearticle
    column:               id
    with_wildcard_routes: true

sousfamillearticle:
  class: sfDoctrineRouteCollection
  options:
    model:                sousfamillearticle
    module:               sousfamillearticle
    prefix_path:          /sousfamillearticle
    column:               id
    with_wildcard_routes: true

fabricant:
  class: sfDoctrineRouteCollection
  options:
    model:                fabricant
    module:               fabricant
    prefix_path:          /fabricant
    column:               id
    with_wildcard_routes: true

famillearticle:
  class: sfDoctrineRouteCollection
  options:
    model:                famillearticle
    module:               famillearticle
    prefix_path:          /famillearticle
    column:               id
    with_wildcard_routes: true



unitemarche:
  class: sfDoctrineRouteCollection
  options:
    model:                unitemarche
    module:               unitemarche
    prefix_path:          /unitemarche
    column:               id
    with_wildcard_routes: true

documentachat:
  class: sfDoctrineRouteCollection
  options:
    model:                documentachat
    module:               documentachat
    prefix_path:          /documentachat
    column:               id
    with_wildcard_routes: true

article:
  class: sfDoctrineRouteCollection
  options:
    model:                article
    module:               article
    prefix_path:          /article
    column:               id
    with_wildcard_routes: true

stock:
  class: sfDoctrineRouteCollection
  options:
    model:                stock
    module:               stock
    prefix_path:          /stock
    column:               id
    with_wildcard_routes: true

magasin:
  class: sfDoctrineRouteCollection
  options:
    model:                magasin
    module:               magasin
    prefix_path:          /magasin
    column:               id
    with_wildcard_routes: true

tva:
  class: sfDoctrineRouteCollection
  options:
    model:                tva
    module:               tva
    prefix_path:          /tva
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: article, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
