generator:
  class: sfDoctrineGenerator
  param:
    model_class:           typeconge
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          typeconge
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          
           
           libelle : { label: "Type Congé"}
           nbrjour : { label: "Nbre Jour"}
           modalitecalcul : { label: "Modalité de Calcul"}
           paye : { label: "Payé "}
           
       
      list:    
          title: Liste des Types Congés
          display: [libelle,nbrjour,modalitecalcul,paye]
      filter:  
          display: [libelle]
      form:    ~
      edit:   
          title: Mise à jour fiche Type Congé
      new: 
          title: Nouvelle fiche Type Congé
